"""Static football-world data: attributes, roles, leagues, clubs, known stars."""

# ---------------------------------------------------------------- attributes
ATTRS = [
    # technical
    "crossing", "dribbling", "finishing", "first_touch", "heading", "long_shots",
    "marking", "passing", "penalty_taking", "set_pieces", "tackling", "technique",
    # mental
    "aggression", "anticipation", "bravery", "composure", "concentration",
    "decisions", "determination", "leadership", "off_the_ball", "positioning",
    "teamwork", "vision", "work_rate",
    # physical
    "acceleration", "agility", "balance", "jumping", "natural_fitness", "pace",
    "stamina", "strength",
    # goalkeeping
    "gk_handling", "gk_reflexes", "gk_one_on_ones", "gk_positioning",
    "gk_aerial", "gk_distribution", "gk_communication", "gk_rushing_out",
]
ATTR_KEYS = [f"a_{a}" for a in ATTRS]
N_ATTR = len(ATTRS)

TECH = ATTRS[0:12]
MENT = ATTRS[12:25]
PHYS = ATTRS[25:33]
GK = ATTRS[33:41]

PERSONALITIES = [
    "Professional", "Ambitious", "Driven", "Loyal", "Reserved", "Determined",
    "Spirited", "Model Citizen", "Fairly Ambitious", "Balanced", "Coward",
    "Mercurial", "Perfectionist", "Light-Hearted", "Stubborn",
]

POSITIONS = ["GK", "DC", "DL", "DR", "DM", "MC", "AMC", "AML", "AMR", "ST"]
POS_GROUPS = {
    "GK": ["GK"],
    "DC": ["DC", "DM"],
    "DL": ["DL", "AML", "DC"],
    "DR": ["DR", "AMR", "DC"],
    "DM": ["DM", "MC", "DC"],
    "MC": ["MC", "DM", "AMC"],
    "AMC": ["AMC", "MC", "ST"],
    "AML": ["AML", "ST", "AMC", "MC"],
    "AMR": ["AMR", "ST", "AMC", "MC"],
    "ST": ["ST", "AMC", "AML", "AMR"],
}
LINES = {"GK": "GK", "DC": "DF", "DL": "DF", "DR": "DF", "DM": "MF",
         "MC": "MF", "AMC": "MF", "AML": "MF", "AMR": "MF", "ST": "FW"}

# role, duty options per position
ROLES = {
    "GK": ["Goalkeeper", "Sweeper Keeper"],
    "DC": ["Central Defender", "Ball Playing Defender", "Wide Centre-Back", "Libero"],
    "DL": ["Full Back", "Wing Back", "Inverted Full Back", "Inverted Wing Back"],
    "DR": ["Full Back", "Wing Back", "Inverted Full Back", "Inverted Wing Back"],
    "DM": ["Anchor", "Defensive Midfielder", "Deep-Lying Playmaker", "Ball-Winning Midfielder", "Roaming Playmaker", "Segundo Volante"],
    "MC": ["Central Midfielder", "Box-to-Box", "Mezzala", "Advanced Playmaker", "Deep-Lying Playmaker", "Ball-Winning Midfielder"],
    "AMC": ["Attacking Midfielder", "Shadow Striker", "Trequartista", "Advanced Playmaker", "Enganche"],
    "AML": ["Winger", "Inside Forward", "Inverted Winger", "Wide Playmaker", "Wide Target Forward"],
    "AMR": ["Winger", "Inside Forward", "Inverted Winger", "Wide Playmaker", "Wide Target Forward"],
    "ST": ["Advanced Forward", "Pressing Forward", "Complete Forward", "Deep-Lying Forward", "Target Forward", "Poacher", "False Nine"],
}
DUTIES = {
    "GK": ["Defend"],
    "DC": ["Defend", "Cover", "Stopper"],
    "DL": ["Defend", "Support", "Attack"],
    "DR": ["Defend", "Support", "Attack"],
    "DM": ["Defend", "Support", "Attack"],
    "MC": ["Defend", "Support", "Attack"],
    "AMC": ["Support", "Attack"],
    "AML": ["Support", "Attack"],
    "AMR": ["Support", "Attack"],
    "ST": ["Attack", "Support"],
}

MENTALITIES = ["Very Defensive", "Defensive", "Cautious", "Balanced", "Positive",
               "Attacking", "Very Attacking"]
MENT_IDX = {m: i for i, m in enumerate(MENTALITIES)}

# instruction option sets
INSTRUCTIONS = {
    "line_of_engagement": ["Much Deeper", "Deeper", "Standard", "Higher", "Much Higher"],
    "defensive_line": ["Much Deeper", "Deeper", "Standard", "Higher", "Much Higher"],
    "tempo": ["Much Lower", "Lower", "Standard", "Higher", "Much Higher"],
    "passing_directness": ["Much Shorter", "Shorter", "Standard", "More Direct", "Much More Direct"],
    "width": ["Much Narrower", "Narrower", "Standard", "Wider", "Much Wider"],
    "pressing_intensity": ["Much Less", "Less", "Standard", "More", "Much More"],
    "time_wasting": ["Never", "Rarely", "Standard", "Frequently", "Always"],
    "play_out_of_defence": [False, True],
    "work_ball_into_box": [False, True],
    "hit_early_crosses": [False, True],
    "dribble_more": [False, True],
    "exploit_middle": [False, True],
    "exploit_flanks": [False, True],
    "counter_press": [False, True],
    "counter_attack": [False, True],
    "offside_trap": [False, True],
    "mark_tighter": [False, True],
}
INSTR_DEFAULT = {k: (v[2] if v[0] != False else False) for k, v in INSTRUCTIONS.items()}

FORMATIONS = {
    "4-3-3 DM Wide": ["GK", "DR", "DC", "DC", "DL", "MC", "MC", "MC", "AMR", "ST", "AML"],
    "4-3-3 DM Narrow": ["GK", "DR", "DC", "DC", "DL", "DM", "MC", "MC", "AMR", "ST", "AML"],
    "4-2-3-1 Wide": ["GK", "DR", "DC", "DC", "DL", "DM", "DM", "AMR", "AMC", "AML", "ST"],
    "4-4-2": ["GK", "DR", "DC", "DC", "DL", "AMR", "MC", "MC", "AML", "ST", "ST"],
    "4-4-2 Diamond": ["GK", "DR", "DC", "DC", "DL", "DM", "AML", "AMR", "AMC", "ST", "ST"],
    "4-1-4-1": ["GK", "DR", "DC", "DC", "DL", "DM", "AMR", "MC", "MC", "AML", "ST"],
    "4-2-2-2": ["GK", "DR", "DC", "DC", "DL", "DM", "DM", "AMR", "AML", "ST", "ST"],
    "4-3-3": ["GK", "DR", "DC", "DC", "DL", "MC", "MC", "AMC", "AMR", "ST", "AML"],
    "3-4-3": ["GK", "DC", "DC", "DC", "AMR", "MC", "MC", "AML", "AMR", "ST", "AML"],
    "3-5-2": ["GK", "DC", "DC", "DC", "AMR", "DM", "MC", "MC", "AML", "ST", "ST"],
    "5-3-2": ["GK", "DL", "DC", "DC", "DC", "DR", "MC", "MC", "AMC", "ST", "ST"],
    "3-4-1-2": ["GK", "DC", "DC", "DC", "AMR", "DM", "DM", "AML", "AMC", "ST", "ST"],
}

TRAINING_SESSIONS = {
    "Recovery": {"fitness": 0, "fatigue": -35, "sharpness": -3, "attrs": {}, "injury": 0.15},
    "Rest": {"fitness": 1.5, "fatigue": -45, "sharpness": -4, "attrs": {}, "injury": 0.05},
    "Fitness": {"fitness": 5, "fatigue": 18, "sharpness": -2, "attrs": {"stamina": 0.5, "natural_fitness": 0.35, "strength": 0.25}, "injury": 1.35},
    "Possession": {"fitness": 1, "fatigue": 8, "sharpness": 1, "attrs": {"first_touch": 0.4, "passing": 0.4, "technique": 0.3, "composure": 0.25, "teamwork": 0.3}, "injury": 0.7},
    "Attacking": {"fitness": 1, "fatigue": 10, "sharpness": 2, "attrs": {"finishing": 0.4, "off_the_ball": 0.4, "vision": 0.3, "long_shots": 0.25, "crossing": 0.25}, "injury": 0.85},
    "Defending": {"fitness": 1, "fatigue": 10, "sharpness": 2, "attrs": {"marking": 0.45, "tackling": 0.4, "positioning": 0.4, "concentration": 0.3, "heading": 0.2}, "injury": 0.85},
    "Transition": {"fitness": 2, "fatigue": 12, "sharpness": 2, "attrs": {"anticipation": 0.35, "decisions": 0.3, "work_rate": 0.3, "acceleration": 0.2}, "injury": 0.9},
    "Pressing": {"fitness": 3, "fatigue": 15, "sharpness": 1, "attrs": {"work_rate": 0.4, "teamwork": 0.35, "aggression": 0.3, "stamina": 0.3}, "injury": 1.1},
    "Build-Up": {"fitness": 1, "fatigue": 8, "sharpness": 1, "attrs": {"passing": 0.4, "first_touch": 0.35, "decisions": 0.3, "vision": 0.3}, "injury": 0.7},
    "Chance Creation": {"fitness": 1, "fatigue": 9, "sharpness": 2, "attrs": {"off_the_ball": 0.4, "dribbling": 0.3, "crossing": 0.3, "passing": 0.3, "composure": 0.2}, "injury": 0.8},
    "Set Pieces": {"fitness": 0, "fatigue": 5, "sharpness": 1, "attrs": {"set_pieces": 0.5, "penalty_taking": 0.35, "heading": 0.25, "jumping": 0.2}, "injury": 0.5},
    "Match Preparation": {"fitness": 0, "fatigue": 6, "sharpness": 5, "attrs": {"concentration": 0.2, "composure": 0.2}, "injury": 0.45},
    "Tactical Familiarity": {"fitness": 0, "fatigue": 6, "sharpness": 1, "attrs": {"decisions": 0.2, "positioning": 0.25, "teamwork": 0.3}, "injury": 0.4},
}

PLAYING_TIME_PROMISES = ["Star Player", "Important Player", "Regular Starter",
                         "Squad Rotation", "Backup", "Hot Prospect", "Development"]
PROMISE_LEVEL = {"Star Player": 6, "Important Player": 5, "Regular Starter": 4,
                 "Squad Rotation": 3, "Backup": 2, "Hot Prospect": 1.5, "Development": 1}

INJURY_TYPES = [
    ("Hamstring strain", 14, 45, ["pace", "acceleration"]),
    ("Calf injury", 10, 35, []),
    ("Ankle ligament damage", 25, 90, []),
    ("Knee ligament (MCL)", 40, 120, []),
    ("Cruciate ligament (ACL)", 150, 300, []),
    ("Groin strain", 15, 50, []),
    ("Concussion", 7, 21, []),
    ("Broken metatarsal", 45, 100, []),
    ("Bruised knee", 5, 18, []),
    ("Muscle fatigue", 3, 12, []),
    ("Shoulder dislocation", 30, 90, []),
    ("Knock", 2, 10, []),
    ("Thigh strain", 12, 40, []),
    ("Back spasm", 7, 25, []),
]

# ------------------------------------------------------------------ leagues
# (code, name, country, tier, size, coef, prestige)
LEAGUES = [
    ("ENG1", "Premier League", "England", 1, 20, 1.00, 95),
    ("ENG2", "Championship", "England", 2, 24, 0.72, 72),
    ("ENG3", "League One", "England", 3, 24, 0.52, 55),
    ("ENG4", "League Two", "England", 4, 24, 0.40, 45),
    ("ENG5", "National League", "England", 5, 24, 0.26, 32),
    ("ESP1", "La Liga", "Spain", 1, 20, 0.95, 93),
    ("ESP2", "Segunda Division", "Spain", 2, 22, 0.62, 62),
    ("ITA1", "Serie A", "Italy", 1, 20, 0.90, 90),
    ("ITA2", "Serie B", "Italy", 2, 20, 0.60, 60),
    ("GER1", "Bundesliga", "Germany", 1, 18, 0.88, 89),
    ("GER2", "2. Bundesliga", "Germany", 2, 18, 0.58, 58),
    ("FRA1", "Ligue 1", "France", 1, 18, 0.80, 82),
    ("FRA2", "Ligue 2", "France", 2, 18, 0.50, 50),
    ("NED1", "Eredivisie", "Netherlands", 1, 18, 0.68, 74),
    ("POR1", "Liga Portugal", "Portugal", 1, 18, 0.66, 72),
    ("SCO1", "Scottish Premiership", "Scotland", 1, 12, 0.55, 62),
    ("SCO2", "Scottish Championship", "Scotland", 2, 10, 0.34, 38),
    ("BEL1", "Belgian Pro League", "Belgium", 1, 16, 0.58, 60),
    ("TUR1", "Super Lig", "Turkey", 1, 19, 0.58, 64),
    ("ARG1", "Liga Profesional", "Argentina", 1, 20, 0.58, 66),
    ("BRA1", "Serie A", "Brazil", 1, 19, 0.62, 68),
    ("USA1", "Major League Soccer", "USA", 1, 24, 0.42, 52),
    ("SAU1", "Saudi Pro League", "Saudi Arabia", 1, 18, 0.50, 58),
]

# (code, name, short, rep, stadium, capacity, country, profile)
CLUBS = [
    # ---- England: Premier League
    ("MCI", "Manchester City", "Man City", 93, "Etihad Stadium", 61000, "England", "elite"),
    ("ARS", "Arsenal", "Arsenal", 92, "Emirates Stadium", 60704, "England", "elite"),
    ("LIV", "Liverpool", "Liverpool", 94, "Anfield", 61276, "England", "elite"),
    ("CHE", "Chelsea", "Chelsea", 90, "Stamford Bridge", 40341, "England", "elite"),
    ("MUN", "Manchester United", "Man Utd", 92, "Old Trafford", 74310, "England", "elite"),
    ("TOT", "Tottenham Hotspur", "Spurs", 87, "Tottenham Hotspur Stadium", 62850, "England", "ucl"),
    ("NEW", "Newcastle United", "Newcastle", 85, "St James' Park", 52305, "England", "ucl"),
    ("AVL", "Aston Villa", "Aston Villa", 84, "Villa Park", 42657, "England", "ucl"),
    ("WHU", "West Ham United", "West Ham", 80, "London Stadium", 62500, "England", "mid"),
    ("BRI", "Brighton & Hove Albion", "Brighton", 78, "Amex Stadium", 31800, "England", "dev"),
    ("BRE", "Brentford", "Brentford", 74, "Gtech Community Stadium", 17250, "England", "sell"),
    ("CRY", "Crystal Palace", "Palace", 76, "Selhurst Park", 25486, "England", "mid"),
    ("FUL", "Fulham", "Fulham", 75, "Craven Cottage", 25700, "England", "mid"),
    ("EVE", "Everton", "Everton", 77, "Hill Dickinson Stadium", 52888, "England", "trad"),
    ("WOL", "Wolverhampton Wanderers", "Wolves", 74, "Molineux", 31750, "England", "mid"),
    ("NOT", "Nottingham Forest", "Forest", 76, "City Ground", 30445, "England", "trad"),
    ("AFC", "AFC Bournemouth", "Bournemouth", 73, "Vitality Stadium", 11307, "England", "sell"),
    ("SUN", "Sunderland", "Sunderland", 68, "Stadium of Light", 48707, "England", "trad"),
    ("LEE", "Leeds United", "Leeds", 72, "Elland Road", 37608, "England", "trad"),
    ("BUR", "Burnley", "Burnley", 66, "Turf Moor", 21944, "England", "minnow"),
    # ---- Championship
    ("LEI", "Leicester City", "Leicester", 74, "King Power Stadium", 32261, "England", "yo-yo"),
    ("SOU", "Southampton", "Southampton", 72, "St Mary's Stadium", 32384, "England", "yo-yo"),
    ("IPS", "Ipswich Town", "Ipswich", 68, "Portman Road", 30311, "England", "yo-yo"),
    ("MID", "Middlesbrough", "Middlesbrough", 70, "Riverside Stadium", 34742, "England", "trad"),
    ("WBA", "West Bromwich Albion", "West Brom", 70, "The Hawthorns", 26688, "England", "trad"),
    ("NOR", "Norwich City", "Norwich", 68, "Carrow Road", 27244, "England", "yo-yo"),
    ("WAT", "Watford", "Watford", 66, "Vicarage Road", 22200, "England", "mid"),
    ("SHE", "Sheffield United", "Sheffield Utd", 68, "Bramall Lane", 32050, "England", "yo-yo"),
    ("SHW", "Sheffield Wednesday", "Sheffield Wed", 64, "Hillsborough", 39732, "England", "trad"),
    ("COV", "Coventry City", "Coventry", 64, "CBS Arena", 32609, "England", "trad"),
    ("BIR", "Birmingham City", "Birmingham", 66, "St Andrew's", 29409, "England", "trad"),
    ("STO", "Stoke City", "Stoke", 64, "bet365 Stadium", 30089, "England", "trad"),
    ("SWA", "Swansea City", "Swansea", 63, "Swansea.com Stadium", 21088, "England", "mid"),
    ("BBR", "Blackburn Rovers", "Blackburn", 63, "Ewood Park", 31367, "England", "trad"),
    ("QPR", "Queens Park Rangers", "QPR", 60, "Loftus Road", 18439, "England", "mid"),
    ("MIL", "Millwall", "Millwall", 59, "The Den", 20146, "England", "minnow"),
    ("PRE", "Preston North End", "Preston", 58, "Deepdale", 23404, "England", "mid"),
    ("BRW", "Bristol City", "Bristol City", 60, "Ashton Gate", 27000, "England", "mid"),
    ("HUL", "Hull City", "Hull", 59, "MKM Stadium", 25586, "England", "mid"),
    ("DER", "Derby County", "Derby", 61, "Pride Park", 33600, "England", "trad"),
    ("POR", "Portsmouth", "Portsmouth", 58, "Fratton Park", 20821, "England", "trad"),
    ("OXU", "Oxford United", "Oxford Utd", 52, "Kassam Stadium", 12500, "England", "minnow"),
    ("CHA", "Charlton Athletic", "Charlton", 55, "The Valley", 27111, "England", "trad"),
    ("MAN", "Mansfield Town", "Mansfield", 43, "One Call Stadium", 8186, "England", "minnow"),
    # ---- League One
    ("BOLT", "Bolton Wanderers", "Bolton", 57, "Toughsheet Community Stadium", 28723, "England", "trad"),
    ("HUD", "Huddersfield Town", "Huddersfield", 56, "John Smith's Stadium", 24121, "England", "trad"),
    ("WIG", "Wigan Athletic", "Wigan", 53, "Brick Community Stadium", 25133, "England", "trad"),
    ("PET", "Peterborough United", "Peterborough", 50, "Weston Homes Stadium", 15314, "England", "sell"),
    ("LIN", "Lincoln City", "Lincoln", 49, "Sincil Bank", 10600, "England", "mid"),
    ("ROT", "Rotherham United", "Rotherham", 48, "New York Stadium", 12021, "England", "yo-yo"),
    ("BUR1", "Burton Albion", "Burton", 42, "Pirelli Stadium", 6912, "England", "minnow"),
    ("BLA", "Blackpool", "Blackpool", 52, "Bloomfield Road", 17338, "England", "trad"),
    ("PLY", "Plymouth Argyle", "Plymouth", 52, "Home Park", 17904, "England", "trad"),
    ("EXE", "Exeter City", "Exeter", 46, "St James Park", 8830, "England", "minnow"),
    ("NHT", "Northampton Town", "Northampton", 45, "Sixfields Stadium", 7798, "England", "minnow"),
    ("REA", "Reading", "Reading", 51, "Select Car Leasing Stadium", 24161, "England", "trad"),
    ("STE", "Stevenage", "Stevenage", 44, "Lamex Stadium", 7800, "England", "minnow"),
    ("WYC", "Wycombe Wanderers", "Wycombe", 45, "Adams Park", 10137, "England", "mid"),
    ("CAM", "Cambridge United", "Cambridge Utd", 44, "Abbey Stadium", 8127, "England", "minnow"),
    ("LEY", "Leyton Orient", "Orient", 45, "Brisbane Road", 9271, "England", "minnow"),
    ("BARNS", "Barnsley", "Barnsley", 48, "Oakwell", 23287, "England", "mid"),
    ("DON", "Doncaster Rovers", "Doncaster", 44, "Eco-Power Stadium", 15231, "England", "minnow"),
    ("MKD", "Milton Keynes Dons", "MK Dons", 47, "Stadium MK", 30500, "England", "mid"),
    ("CAR", "Cardiff City", "Cardiff", 58, "Cardiff City Stadium", 33280, "Wales", "trad"),
    ("LUT", "Luton Town", "Luton", 55, "Kenilworth Road", 11500, "England", "yo-yo"),
    ("BRC", "Bradford City", "Bradford", 50, "University of Bradford Stadium", 24433, "England", "trad"),
    ("STC", "Stockport County", "Stockport", 48, "Edgeley Park", 10852, "England", "mid"),
    ("WXC", "Wrexham", "Wrexham", 52, "Racecourse Ground", 13341, "Wales", "minnow"),
    # ---- League Two
    ("WAL", "Walsall", "Walsall", 42, "Bescot Stadium", 11300, "England", "mid"),
    ("NOC", "Notts County", "Notts County", 46, "Meadow Lane", 19588, "England", "trad"),
    ("CHE1", "Chesterfield", "Chesterfield", 44, "SMH Group Stadium", 10504, "England", "mid"),
    ("GIL", "Gillingham", "Gillingham", 41, "Priestfield Stadium", 11582, "England", "minnow"),
    ("SWI", "Swindon Town", "Swindon", 43, "County Ground", 15728, "England", "trad"),
    ("COL", "Colchester United", "Colchester", 41, "JobServe Community Stadium", 10105, "England", "minnow"),
    ("TRA", "Tranmere Rovers", "Tranmere", 40, "Prenton Park", 16789, "England", "trad"),
    ("SAL", "Salford City", "Salford", 40, "Moor Lane", 5108, "England", "minnow"),
    ("HAR", "Harrogate Town", "Harrogate", 36, "Wetherby Road", 5000, "England", "minnow"),
    ("BAR1", "Barnet", "Barnet", 37, "The Hive Stadium", 6418, "England", "minnow"),
    ("CRE", "Crewe Alexandra", "Crewe", 39, "Mornflake Stadium", 10153, "England", "dev"),
    ("FLE", "Fleetwood Town", "Fleetwood", 36, "Highbury Stadium", 5311, "England", "minnow"),
    ("SHR", "Shrewsbury Town", "Shrewsbury", 39, "New Meadow", 9875, "England", "minnow"),
    ("BRO", "Bromley", "Bromley", 36, "Hayes Lane", 5300, "England", "minnow"),
    ("ACC", "Accrington Stanley", "Accrington", 34, "Wham Stadium", 5450, "England", "minnow"),
    ("NEW1", "Newport County", "Newport", 36, "Rodney Parade", 7850, "Wales", "minnow"),
    ("CRA", "Crawley Town", "Crawley", 35, "Broadfield Stadium", 5996, "England", "minnow"),
    ("MOR", "Morecambe", "Morecambe", 33, "Mazuma Mobile Stadium", 6476, "England", "minnow"),
    ("OLD", "Oldham Athletic", "Oldham", 40, "Boundary Park", 13513, "England", "trad"),
    ("CHE2", "Cheltenham Town", "Cheltenham", 36, "Whaddon Road", 7066, "England", "minnow"),
    ("BRI1", "Bristol Rovers", "Bristol Rovers", 44, "Memorial Stadium", 9832, "England", "trad"),
    ("GRI", "Grimsby Town", "Grimsby", 40, "Blundell Park", 9052, "England", "trad"),
    ("BRR", "Barrow", "Barrow", 36, "Holker Street", 6500, "England", "minnow"),
    ("YEO", "Yeovil Town", "Yeovil", 33, "Huish Park", 9565, "England", "minnow"),
    # ---- National League (semi-pro)
    ("ROC", "Rochdale", "Rochdale", 33, "Spotland Stadium", 10249, "England", "trad"),
    ("SOU1", "Southend United", "Southend", 36, "Roots Hall", 12392, "England", "trad"),
    ("YOR", "York City", "York", 34, "LNER Community Stadium", 8500, "England", "mid"),
    ("HAL", "Halifax Town", "Halifax", 29, "The Shay", 14081, "England", "minnow"),
    ("GAT", "Gateshead", "Gateshead", 28, "Gateshead International Stadium", 11800, "England", "minnow"),
    ("SOL", "Solihull Moors", "Solihull", 27, "Armoury Stadium", 5500, "England", "minnow"),
    ("EAS", "Eastleigh", "Eastleigh", 26, "Ten Acres", 5250, "England", "minnow"),
    ("ALD", "Aldershot Town", "Aldershot", 27, "EBB Stadium", 7100, "England", "trad"),
    ("WOK", "Woking", "Woking", 26, "Kingfield Stadium", 6036, "England", "minnow"),
    ("BOS", "Boston United", "Boston Utd", 26, "Jakemans Community Stadium", 5061, "England", "trad"),
    ("TAM", "Tamworth", "Tamworth", 24, "The Lamb Ground", 4065, "England", "minnow"),
    ("FGR", "Forest Green Rovers", "Forest Green", 30, "The New Lawn", 5147, "England", "minnow"),
    ("HAR1", "Hartlepool United", "Hartlepool", 31, "Victoria Park", 7856, "England", "trad"),
    ("SCU", "Scunthorpe United", "Scunthorpe", 30, "Attis Arena", 9088, "England", "trad"),
    ("WEA", "Wealdstone", "Wealdstone", 23, "Grosvenor Vale", 4085, "England", "minnow"),
    ("SUT", "Sutton United", "Sutton", 26, "Gander Green Lane", 5013, "England", "minnow"),
    ("DAG", "Dagenham & Redbridge", "Dagenham", 24, "Chigwell Construction Stadium", 6078, "England", "minnow"),
    ("MAI", "Maidenhead United", "Maidenhead", 22, "York Road", 4000, "England", "minnow"),
    ("CHE3", "Chester FC", "Chester", 23, "Deva Stadium", 6500, "England", "trad"),
    ("KID", "Kidderminster Harriers", "Kidderminster", 22, "Aggborough Stadium", 6238, "England", "minnow"),
    ("CUR", "Curzon Ashton", "Curzon Ashton", 20, "Tameside Stadium", 4000, "England", "minnow"),
    ("BLY", "Blyth Spartans", "Blyth", 21, "Croft Park", 4435, "England", "trad"),
    ("FAR", "Farnborough", "Farnborough", 21, "Cherrywood Road", 7000, "England", "minnow"),
    ("TON", "Tonbridge Angels", "Tonbridge", 19, "Longmead Stadium", 3000, "England", "minnow"),
    # ---- Spain: La Liga
    ("RMA", "Real Madrid", "Real Madrid", 97, "Santiago Bernabeu", 81044, "Spain", "elite"),
    ("BAR", "Barcelona", "Barcelona", 95, "Estadi Olimpic Lluis Companys", 55926, "Spain", "elite"),
    ("ATM", "Atletico Madrid", "Atletico", 90, "Metropolitano", 70460, "Spain", "elite"),
    ("ATH", "Athletic Club", "Athletic", 84, "San Mames", 53289, "Spain", "dev"),
    ("RSC", "Real Sociedad", "Real Sociedad", 82, "Reale Arena", 39500, "Spain", "dev"),
    ("VIL", "Villarreal", "Villarreal", 81, "La Ceramica", 23500, "Spain", "ucl"),
    ("BET", "Real Betis", "Betis", 80, "Benito Villamarin", 60721, "Spain", "ucl"),
    ("SEV", "Sevilla", "Sevilla", 82, "Ramon Sanchez-Pizjuan", 43883, "Spain", "trad"),
    ("VAL", "Valencia", "Valencia", 79, "Mestalla", 49430, "Spain", "trad"),
    ("CELT", "Celta Vigo", "Celta", 73, "Balaidos", 29000, "Spain", "mid"),
    ("GIR", "Girona", "Girona", 74, "Montilivi", 14286, "Spain", "sell"),
    ("RAY", "Rayo Vallecano", "Rayo", 70, "Vallecas", 14708, "Spain", "mid"),
    ("OSA", "Osasuna", "Osasuna", 69, "El Sadar", 23576, "Spain", "mid"),
    ("GET", "Getafe", "Getafe", 68, "Coliseum", 17393, "Spain", "mid"),
    ("ALA", "Deportivo Alaves", "Alaves", 66, "Mendizorroza", 19840, "Spain", "mid"),
    ("ESP", "Espanyol", "Espanyol", 68, "RCDE Stadium", 40000, "Spain", "trad"),
    ("RCD", "Deportivo La Coruna", "Deportivo", 66, "Riazor", 32490, "Spain", "trad"),
    ("MLL", "Real Mallorca", "Mallorca", 67, "Son Moix", 23142, "Spain", "mid"),
    ("ELC", "Elche", "Elche", 62, "Martinez Valero", 33732, "Spain", "minnow"),
    ("LEV", "Levante", "Levante", 61, "Ciutat de Valencia", 26354, "Spain", "minnow"),
    # ---- Spain: Segunda
    ("RAC", "Racing Santander", "Racing", 55, "El Sardinero", 22222, "Spain", "trad"),
    ("ZAR", "Real Zaragoza", "Zaragoza", 62, "La Romareda", 33608, "Spain", "trad"),
    ("GRA", "Granada", "Granada", 60, "Nuevo Los Carmenes", 19336, "Spain", "yo-yo"),
    ("CAD", "Cadiz", "Cadiz", 58, "Nuevo Mirandilla", 20724, "Spain", "yo-yo"),
    ("LEG", "Leganes", "Leganes", 56, "Butarque", 12454, "Spain", "yo-yo"),
    ("VLL", "Real Valladolid", "Valladolid", 59, "Jose Zorrilla", 27846, "Spain", "yo-yo"),
    ("SPG", "Sporting Gijon", "Sporting", 58, "El Molinon", 30000, "Spain", "trad"),
    ("OVI", "Real Oviedo", "Oviedo", 56, "Carlos Tartiere", 30500, "Spain", "trad"),
    ("TNE", "Tenerife", "Tenerife", 52, "Heliodoro Rodriguez Lopez", 22824, "Spain", "mid"),
    ("LPA", "Las Palmas", "Las Palmas", 58, "Gran Canaria", 32392, "Spain", "yo-yo"),
    ("ALM", "Almeria", "Almeria", 54, "Power Horse Stadium", 15000, "Spain", "mid"),
    ("EIB", "Eibar", "Eibar", 52, "Ipurua", 8164, "Spain", "mid"),
    ("HUE", "Huesca", "Huesca", 48, "El Alcoraz", 9128, "Spain", "minnow"),
    ("CAR1", "Cartagena", "Cartagena", 45, "Cartagonova", 15105, "Spain", "minnow"),
    ("ALB", "Albacete", "Albacete", 47, "Carlos Belmonte", 17524, "Spain", "minnow"),
    ("BUR1E", "Burgos", "Burgos", 46, "El Plantio", 12640, "Spain", "minnow"),
    ("ELD", "Eldense", "Eldense", 41, "Nuevo Pepico Amat", 5000, "Spain", "minnow"),
    ("MIR", "Mirandes", "Mirandes", 44, "Anduva", 5759, "Spain", "minnow"),
    ("CAS", "Castellon", "Castellon", 47, "SkyFi Castalia", 15500, "Spain", "mid"),
    ("COR", "Cordoba", "Cordoba", 49, "Nuevo Arcangel", 21822, "Spain", "trad"),
    ("MAL", "Malaga", "Malaga", 56, "La Rosaleda", 30044, "Spain", "trad"),
    ("RFE", "Racing Ferrol", "Ferrol", 40, "A Malata", 12043, "Spain", "minnow"),
    # ---- Italy: Serie A
    ("INT", "Inter Milan", "Inter", 93, "San Siro", 75923, "Italy", "elite"),
    ("JUV", "Juventus", "Juventus", 90, "Allianz Stadium", 41507, "Italy", "elite"),
    ("ACM", "AC Milan", "Milan", 90, "San Siro", 75923, "Italy", "elite"),
    ("NAP", "Napoli", "Napoli", 88, "Diego Armando Maradona", 54726, "Italy", "elite"),
    ("ROM", "Roma", "Roma", 85, "Olimpico", 70634, "Italy", "ucl"),
    ("LAZ", "Lazio", "Lazio", 82, "Olimpico", 70634, "Italy", "ucl"),
    ("ATA", "Atalanta", "Atalanta", 84, "Gewiss Stadium", 21300, "Italy", "dev"),
    ("FIO", "Fiorentina", "Fiorentina", 79, "Artemio Franchi", 43147, "Italy", "mid"),
    ("BOL", "Bologna", "Bologna", 78, "Renato Dall'Ara", 36462, "Italy", "mid"),
    ("TOR", "Torino", "Torino", 74, "Olimpico Grande Torino", 27994, "Italy", "trad"),
    ("UDI", "Udinese", "Udinese", 71, "Bluenergy Stadium", 25144, "Italy", "sell"),
    ("GEN", "Genoa", "Genoa", 70, "Luigi Ferraris", 36599, "Italy", "trad"),
    ("CAG", "Cagliari", "Cagliari", 68, "Unipol Domus", 16416, "Italy", "mid"),
    ("LEC", "Lecce", "Lecce", 64, "Via del Mare", 33876, "Italy", "minnow"),
    ("EMP", "Empoli", "Empoli", 64, "Carlo Castellani", 16284, "Italy", "dev"),
    ("PAR", "Parma", "Parma", 67, "Ennio Tardini", 27906, "Italy", "trad"),
    ("COM", "Como", "Como", 66, "Giuseppe Sinigaglia", 13602, "Italy", "mid"),
    ("VER", "Hellas Verona", "Verona", 66, "Marcantonio Bentegodi", 39211, "Italy", "mid"),
    ("SAS", "Sassuolo", "Sassuolo", 64, "Mapei Stadium", 21525, "Italy", "yo-yo"),
    ("PIS", "Pisa", "Pisa", 58, "Arena Garibaldi", 14000, "Italy", "minnow"),
    # ---- Italy: Serie B
    ("SAM", "Sampdoria", "Sampdoria", 70, "Luigi Ferraris", 36599, "Italy", "trad"),
    ("PAL", "Palermo", "Palermo", 68, "Renzo Barbera", 36365, "Italy", "trad"),
    ("CRE1", "Cremonese", "Cremonese", 62, "Giovanni Zini", 20641, "Italy", "yo-yo"),
    ("SPE", "Spezia", "Spezia", 58, "Alberto Picco", 11968, "Italy", "mid"),
    ("BRE1", "Brescia", "Brescia", 60, "Mario Rigamonti", 19500, "Italy", "trad"),
    ("BAR1I", "Bari", "Bari", 62, "San Nicola", 58270, "Italy", "trad"),
    ("MOD", "Modena", "Modena", 55, "Alberto Braglia", 21151, "Italy", "mid"),
    ("REG", "Reggiana", "Reggiana", 52, "Citta del Tricolore", 21584, "Italy", "mid"),
    ("CAT", "Catanzaro", "Catanzaro", 54, "Nicola Ceravolo", 14650, "Italy", "mid"),
    ("JST", "Juve Stabia", "Juve Stabia", 45, "Romeo Menti", 7642, "Italy", "minnow"),
    ("SUD", "Sudtirol", "Sudtirol", 46, "Druso Stadium", 5539, "Italy", "minnow"),
    ("CIT", "Cittadella", "Cittadella", 48, "Pier Cesare Tombolato", 7623, "Italy", "minnow"),
    ("PES", "Pescara", "Pescara", 52, "Adriatico", 20500, "Italy", "trad"),
    ("FRO", "Frosinone", "Frosinone", 54, "Benito Stirpe", 16227, "Italy", "yo-yo"),
    ("SAL1", "Salernitana", "Salernitana", 56, "Arechi", 37800, "Italy", "yo-yo"),
    ("MON", "Monza", "Monza", 58, "U-Power Stadium", 16917, "Italy", "yo-yo"),
    ("VEN", "Venezia", "Venezia", 56, "Pier Luigi Penzo", 11150, "Italy", "yo-yo"),
    ("AVL1", "Avellino", "Avellino", 48, "Partenio-Lombardi", 10110, "Italy", "trad"),
    ("PAD", "Padova", "Padova", 49, "Euganeo", 32420, "Italy", "trad"),
    ("MAN1", "Mantova", "Mantova", 45, "Danilo Martelli", 14884, "Italy", "minnow"),
    # ---- Germany: Bundesliga
    ("BAY", "Bayern Munich", "Bayern", 95, "Allianz Arena", 75024, "Germany", "elite"),
    ("BVB", "Borussia Dortmund", "Dortmund", 90, "Signal Iduna Park", 81365, "Germany", "elite"),
    ("LEV1", "Bayer Leverkusen", "Leverkusen", 88, "BayArena", 30210, "Germany", "elite"),
    ("RBL", "RB Leipzig", "Leipzig", 86, "Red Bull Arena", 47069, "Germany", "dev"),
    ("SGE", "Eintracht Frankfurt", "Frankfurt", 83, "Deutsche Bank Park", 58000, "Germany", "ucl"),
    ("VFB", "VfB Stuttgart", "Stuttgart", 80, "MHPArena", 60058, "Germany", "ucl"),
    ("BMG", "Borussia Monchengladbach", "Gladbach", 78, "Borussia-Park", 54042, "Germany", "trad"),
    ("WOB", "VfL Wolfsburg", "Wolfsburg", 76, "Volkswagen Arena", 30000, "Germany", "mid"),
    ("TSG", "TSG Hoffenheim", "Hoffenheim", 74, "PreZero Arena", 30150, "Germany", "dev"),
    ("SCF", "SC Freiburg", "Freiburg", 75, "Europa-Park Stadion", 34700, "Germany", "mid"),
    ("FCU", "Union Berlin", "Union Berlin", 70, "An der Alten Forsterei", 22012, "Germany", "mid"),
    ("FCSP", "St Pauli", "St Pauli", 66, "Millerntor-Stadion", 29546, "Germany", "trad"),
    ("WER", "Werder Bremen", "Bremen", 76, "Weserstadion", 42100, "Germany", "trad"),
    ("FCA", "FC Augsburg", "Augsburg", 68, "WWK Arena", 30660, "Germany", "mid"),
    ("MAI1", "Mainz 05", "Mainz", 72, "MEWA Arena", 34034, "Germany", "mid"),
    ("HAI", "Heidenheim", "Heidenheim", 64, "Voith-Arena", 15000, "Germany", "minnow"),
    ("FCN1", "Hamburger SV", "Hamburg", 74, "Volksparkstadion", 57000, "Germany", "trad"),
    ("KOE", "FC Koln", "Koln", 72, "RheinEnergieStadion", 50000, "Germany", "trad"),
    # ---- 2. Bundesliga
    ("SCH", "Schalke 04", "Schalke", 74, "Veltins-Arena", 62271, "Germany", "trad"),
    ("HSVI", "Hertha BSC", "Hertha", 72, "Olympiastadion", 74649, "Germany", "trad"),
    ("D98", "Darmstadt 98", "Darmstadt", 58, "Merck-Stadion am Bollenfalltor", 17810, "Germany", "minnow"),
    ("FCN", "1. FC Nurnberg", "Nurnberg", 64, "Max-Morlock-Stadion", 50000, "Germany", "trad"),
    ("KAI", "1. FC Kaiserslautern", "Kaiserslautern", 66, "Fritz-Walter-Stadion", 49327, "Germany", "trad"),
    ("DYN", "Dynamo Dresden", "Dresden", 58, "Rudolf-Harbig-Stadion", 32085, "Germany", "trad"),
    ("HAN", "Hannover 96", "Hannover", 64, "Heinz von Heiden Arena", 49000, "Germany", "trad"),
    ("DUS", "Fortuna Dusseldorf", "Dusseldorf", 62, "Merkur Spiel-Arena", 54600, "Germany", "trad"),
    ("SCP", "SC Paderborn", "Paderborn", 56, "Home Deluxe Arena", 15000, "Germany", "minnow"),
    ("KSV", "Holstein Kiel", "Kiel", 58, "Holstein-Stadion", 15034, "Germany", "yo-yo"),
    ("SVD", "Elversberg", "Elversberg", 48, "Waldstadion Kaiserlinde", 10000, "Germany", "minnow"),
    ("F95", "Greuther Furth", "Furth", 54, "Sportpark Ronhof", 16626, "Germany", "minnow"),
    ("MAG", "1. FC Magdeburg", "Magdeburg", 52, "Avnet Arena", 27500, "Germany", "trad"),
    ("EBS", "Eintracht Braunschweig", "Braunschweig", 52, "Eintracht-Stadion", 23325, "Germany", "trad"),
    ("PRM", "Preussen Munster", "Munster", 46, "Preussenstadion", 14300, "Germany", "minnow"),
    ("SSV", "SSV Ulm", "Ulm", 46, "Donaustadion", 19500, "Germany", "minnow"),
    ("KSC", "Karlsruher SC", "Karlsruhe", 56, "Wildparkstadion", 29699, "Germany", "trad"),
    ("BOC", "VfL Bochum", "Bochum", 60, "Vonovia Ruhrstadion", 26000, "Germany", "yo-yo"),
    # ---- France: Ligue 1
    ("PSG", "Paris Saint-Germain", "PSG", 95, "Parc des Princes", 47929, "France", "elite"),
    ("OM", "Marseille", "Marseille", 85, "Orange Velodrome", 67394, "France", "elite"),
    ("ASM", "Monaco", "Monaco", 84, "Stade Louis-II", 18523, "Monaco", "dev"),
    ("LOSC", "Lille", "Lille", 80, "Decathlon Arena", 50157, "France", "dev"),
    ("OL", "Lyon", "Lyon", 83, "Groupama Stadium", 59186, "France", "trad"),
    ("NIC", "Nice", "Nice", 77, "Allianz Riviera", 36178, "France", "mid"),
    ("REN", "Rennes", "Rennes", 77, "Roazhon Park", 29778, "France", "mid"),
    ("RCL", "Lens", "Lens", 75, "Bollaert-Delelis", 38223, "France", "trad"),
    ("STR", "Strasbourg", "Strasbourg", 72, "Stade de la Meinau", 26109, "France", "mid"),
    ("TFC", "Toulouse", "Toulouse", 70, "Stadium de Toulouse", 33150, "France", "mid"),
    ("BRE1F", "Brest", "Brest", 68, "Stade Francis-Le Ble", 15220, "France", "mid"),
    ("NAN", "Nantes", "Nantes", 70, "Stade de la Beaujoire", 35322, "France", "trad"),
    ("SR", "Stade de Reims", "Reims", 67, "Stade Auguste-Delaune", 21029, "France", "trad"),
    ("HAV", "Le Havre", "Le Havre", 62, "Stade Oceane", 25178, "France", "minnow"),
    ("AJA", "Auxerre", "Auxerre", 64, "Stade Abbe-Deschamps", 18541, "France", "trad"),
    ("ANG", "Angers", "Angers", 62, "Stade Raymond Kopa", 18752, "France", "minnow"),
    ("MET", "Metz", "Metz", 62, "Stade Saint-Symphorien", 30000, "France", "yo-yo"),
    ("LOR", "Lorient", "Lorient", 62, "Stade du Moustoir", 18890, "France", "yo-yo"),
    # ---- Ligue 2
    ("ASSE", "Saint-Etienne", "Saint-Etienne", 74, "Stade Geoffroy-Guichard", 41965, "France", "trad"),
    ("GBX", "Girondins de Bordeaux", "Bordeaux", 68, "Matmut Atlantique", 42115, "France", "trad"),
    ("SMC", "Caen", "Caen", 62, "Stade Michel d'Ornano", 21215, "France", "trad"),
    ("GFC", "Grenoble", "Grenoble", 56, "Stade des Alpes", 20068, "France", "mid"),
    ("PAU", "Pau FC", "Pau", 52, "Nouste Camp", 4500, "France", "minnow"),
    ("AMI", "Amiens", "Amiens", 56, "Stade de la Licorne", 12097, "France", "mid"),
    ("GUI", "Guingamp", "Guingamp", 58, "Stade de Roudourou", 18378, "France", "trad"),
    ("TRO", "Troyes", "Troyes", 58, "Stade de l'Aube", 20400, "France", "yo-yo"),
    ("LAVAL", "Laval", "Laval", 50, "Stade Francis Le Basser", 11107, "France", "minnow"),
    ("ROD", "Rodez", "Rodez", 48, "Stade Paul-Lignon", 5955, "France", "minnow"),
    ("RED", "Red Star", "Red Star", 48, "Stade Bauer", 3000, "France", "trad"),
    ("MAR", "Martigues", "Martigues", 42, "Stade Francis Turcan", 11000, "France", "minnow"),
    ("AJA2", "Annecy", "Annecy", 46, "Parc des Sports", 15660, "France", "minnow"),
    ("BAST", "Bastia", "Bastia", 56, "Stade Armand Cesari", 16078, "France", "trad"),
    ("CLE", "Clermont Foot", "Clermont", 56, "Stade Gabriel Montpied", 11980, "France", "yo-yo"),
    ("DUN", "Dunkerque", "Dunkerque", 48, "Stade Marcel-Tribut", 4933, "France", "minnow"),
    ("PARIS", "Paris FC", "Paris FC", 60, "Stade Sebastien Charlety", 20000, "France", "mid"),
    ("CON", "Concarneau", "Concarneau", 42, "Stade Guy Piriou", 6500, "France", "minnow"),
    # ---- Netherlands: Eredivisie
    ("AJA1", "Ajax", "Ajax", 87, "Johan Cruijff ArenA", 55865, "Netherlands", "dev"),
    ("PSV", "PSV Eindhoven", "PSV", 85, "Philips Stadion", 35000, "Netherlands", "dev"),
    ("FEY", "Feyenoord", "Feyenoord", 84, "De Kuip", 47500, "Netherlands", "trad"),
    ("AZ", "AZ Alkmaar", "AZ", 76, "AFAS Stadion", 17023, "Netherlands", "dev"),
    ("TWE", "FC Twente", "Twente", 74, "De Grolsch Veste", 30205, "Netherlands", "mid"),
    ("UTR", "FC Utrecht", "Utrecht", 72, "Stadion Galgenwaard", 23750, "Netherlands", "mid"),
    ("VIT", "Vitesse", "Vitesse", 64, "GelreDome", 21248, "Netherlands", "trad"),
    ("HEE", "Heerenveen", "Heerenveen", 66, "Abe Lenstra Stadion", 27224, "Netherlands", "dev"),
    ("GRO", "FC Groningen", "Groningen", 64, "Euroborg", 22550, "Netherlands", "mid"),
    ("NEC", "NEC Nijmegen", "NEC", 62, "Goffertstadion", 12500, "Netherlands", "mid"),
    ("PEC", "PEC Zwolle", "Zwolle", 56, "MAC3PARK Stadion", 14000, "Netherlands", "minnow"),
    ("SPR", "Sparta Rotterdam", "Sparta", 58, "Sparta Stadion Het Kasteel", 11026, "Netherlands", "mid"),
    ("GAE", "Go Ahead Eagles", "Go Ahead", 58, "De Adelaarshorst", 10400, "Netherlands", "mid"),
    ("FOR", "Fortuna Sittard", "Fortuna", 54, "Fortuna Sittard Stadion", 12500, "Netherlands", "minnow"),
    ("RKC", "RKC Waalwijk", "RKC", 50, "Mandemakers Stadion", 7508, "Netherlands", "minnow"),
    ("ALME", "Almere City", "Almere", 50, "Yanmar Stadion", 4900, "Netherlands", "minnow"),
    ("WIL", "Willem II", "Willem II", 56, "Koning Willem II Stadion", 14500, "Netherlands", "trad"),
    ("NAC", "NAC Breda", "NAC", 56, "Rat Verlegh Stadion", 19000, "Netherlands", "trad"),
    # ---- Portugal
    ("SLB", "Benfica", "Benfica", 86, "Estadio da Luz", 64642, "Portugal", "dev"),
    ("FCP", "FC Porto", "Porto", 85, "Estadio do Dragao", 50033, "Portugal", "dev"),
    ("SPORT", "Sporting CP", "Sporting", 85, "Estadio Jose Alvalade", 50095, "Portugal", "dev"),
    ("SCB", "SC Braga", "Braga", 76, "Estadio Municipal de Braga", 30286, "Portugal", "mid"),
    ("VSC", "Vitoria de Guimaraes", "Guimaraes", 70, "Estadio D. Afonso Henriques", 30029, "Portugal", "mid"),
    ("BFS", "Boavista", "Boavista", 62, "Estadio do Bessa", 28263, "Portugal", "trad"),
    ("RIO", "Rio Ave", "Rio Ave", 60, "Estadio dos Arcos", 12818, "Portugal", "mid"),
    ("FAM", "Famalicao", "Famalicao", 58, "Estadio Municipal de Famalicao", 5307, "Portugal", "mid"),
    ("ARO", "Arouca", "Arouca", 56, "Estadio Municipal de Arouca", 5600, "Portugal", "minnow"),
    ("GVE", "Gil Vicente", "Gil Vicente", 56, "Estadio Cidade de Barcelos", 12504, "Portugal", "minnow"),
    ("EST", "Estoril Praia", "Estoril", 56, "Estadio Antonio Coimbra da Mota", 8015, "Portugal", "minnow"),
    ("CAS1", "Casa Pia", "Casa Pia", 52, "Estadio Nacional", 37593, "Portugal", "minnow"),
    ("MORE", "Moreirense", "Moreirense", 54, "Parque de Jogos Comendador Joaquim", 6153, "Portugal", "minnow"),
    ("FARE", "Farense", "Farense", 52, "Estadio de Sao Luis", 7000, "Portugal", "minnow"),
    ("SAN", "Santa Clara", "Santa Clara", 54, "Estadio de Sao Miguel", 12500, "Portugal", "minnow"),
    ("NAC1", "Nacional", "Nacional", 52, "Estadio da Madeira", 5132, "Portugal", "minnow"),
    ("AVS", "AVS", "AVS", 48, "Estadio do CD Aves", 7000, "Portugal", "minnow"),
    ("EST1", "Estrela da Amadora", "Estrela", 50, "Estadio Jose Gomes", 9288, "Portugal", "minnow"),
    # ---- Scotland
    ("CEL", "Celtic", "Celtic", 78, "Celtic Park", 60411, "Scotland", "elite"),
    ("RAN", "Rangers", "Rangers", 77, "Ibrox Stadium", 50817, "Scotland", "elite"),
    ("ABE", "Aberdeen", "Aberdeen", 64, "Pittodrie Stadium", 20866, "Scotland", "trad"),
    ("HIB", "Hibernian", "Hibernian", 62, "Easter Road", 20421, "Scotland", "trad"),
    ("HRT", "Hearts", "Hearts", 64, "Tynecastle Park", 20099, "Scotland", "trad"),
    ("DUNU", "Dundee United", "Dundee Utd", 56, "Tannadice Park", 14223, "Scotland", "trad"),
    ("DUND", "Dundee", "Dundee", 54, "Dens Park", 11775, "Scotland", "trad"),
    ("KIL", "Kilmarnock", "Kilmarnock", 56, "Rugby Park", 15000, "Scotland", "mid"),
    ("MOT", "Motherwell", "Motherwell", 55, "Fir Park", 13677, "Scotland", "mid"),
    ("STM", "St Mirren", "St Mirren", 52, "SMISA Stadium", 7937, "Scotland", "minnow"),
    ("ROS", "Ross County", "Ross County", 46, "Global Energy Stadium", 6541, "Scotland", "minnow"),
    ("LIV1", "Livingston", "Livingston", 46, "Almondvale Stadium", 9512, "Scotland", "minnow"),
    ("DUN2", "Dunfermline", "Dunfermline", 46, "East End Park", 11480, "Scotland", "trad"),
    ("AIR", "Airdrieonians", "Airdrie", 40, "Excelsior Stadium", 10101, "Scotland", "minnow"),
    ("GRC", "Greenock Morton", "Morton", 42, "Cappielow Park", 11589, "Scotland", "trad"),
    ("AIK1", "Ayr United", "Ayr", 42, "Somerset Park", 10185, "Scotland", "trad"),
    ("PAR1", "Partick Thistle", "Partick", 46, "Firhill Stadium", 10102, "Scotland", "trad"),
    ("RAI", "Raith Rovers", "Raith", 44, "Stark's Park", 8867, "Scotland", "trad"),
    ("QUE", "Queen's Park", "Queens Park", 42, "Lesser Hampden", 8100, "Scotland", "trad"),
    ("ARB", "Arbroath", "Arbroath", 38, "Gayfield Park", 6600, "Scotland", "minnow"),
    ("STR1", "Stirling Albion", "Stirling", 36, "Forthbank Stadium", 3808, "Scotland", "minnow"),
    ("PET1", "Peterhead", "Peterhead", 32, "Balmoor Stadium", 3150, "Scotland", "minnow"),
    # ---- Belgium
    ("CLU", "Club Brugge", "Club Brugge", 76, "Jan Breydel Stadium", 29062, "Belgium", "dev"),
    ("AND", "Anderlecht", "Anderlecht", 76, "Lotto Park", 21500, "Belgium", "dev"),
    ("GENK", "KRC Genk", "Genk", 74, "Cegeka Arena", 24956, "Belgium", "dev"),
    ("GNT", "KAA Gent", "Gent", 70, "Ghelamco Arena", 20000, "Belgium", "mid"),
    ("ANT", "Royal Antwerp", "Antwerp", 70, "Bosuilstadion", 12975, "Belgium", "trad"),
    ("STL", "Standard Liege", "Standard", 70, "Stade Maurice Dufrasne", 30023, "Belgium", "trad"),
    ("RSC1", "Charleroi", "Charleroi", 62, "Stade du Pays de Charleroi", 14000, "Belgium", "mid"),
    ("CER", "Cercle Brugge", "Cercle", 62, "Jan Breydel Stadium", 29062, "Belgium", "mid"),
    ("OHM", "Oud-Heverlee Leuven", "Leuven", 58, "Den Dreef", 10000, "Belgium", "minnow"),
    ("WES", "Westerlo", "Westerlo", 56, "Het Kuipje", 8035, "Belgium", "minnow"),
    ("STT", "Sint-Truiden", "Sint-Truiden", 56, "Stayen", 14600, "Belgium", "minnow"),
    ("MEC", "KV Mechelen", "Mechelen", 60, "AFAS-stadion Achter de Kazerne", 16700, "Belgium", "mid"),
    ("KOR", "Kortrijk", "Kortrijk", 54, "Guldensporen Stadion", 9399, "Belgium", "minnow"),
    ("EUP", "Eupen", "Eupen", 48, "Kehrwegstadion", 8363, "Belgium", "minnow"),
    ("DENDER", "Dender", "Dender", 46, "Van Roystadion", 4500, "Belgium", "minnow"),
    ("BEE", "Beerschot", "Beerschot", 52, "Olympisch Stadion", 12771, "Belgium", "trad"),
    # ---- Turkey
    ("GAL", "Galatasaray", "Galatasaray", 80, "Rams Park", 52223, "Turkey", "elite"),
    ("FEN", "Fenerbahce", "Fenerbahce", 80, "Sukru Saracoglu", 47834, "Turkey", "elite"),
    ("BJK", "Besiktas", "Besiktas", 77, "Tupras Stadium", 42590, "Turkey", "trad"),
    ("TSB", "Trabzonspor", "Trabzonspor", 72, "Papara Park", 40782, "Turkey", "trad"),
    ("BAS", "Basaksehir", "Basaksehir", 64, "Fatih Terim Stadium", 17156, "Turkey", "mid"),
    ("KON", "Konyaspor", "Konyaspor", 58, "Konya Buyuksehir Stadium", 42000, "Turkey", "mid"),
    ("ANT1", "Antalyaspor", "Antalyaspor", 56, "Corendon Airlines Park", 32537, "Turkey", "mid"),
    ("KAS", "Kasimpasa", "Kasimpasa", 54, "Recep Tayyip Erdogan Stadium", 14234, "Turkey", "mid"),
    ("SIV", "Sivasspor", "Sivasspor", 52, "Sivas 4 Eylul Stadium", 27532, "Turkey", "mid"),
    ("GAZ", "Gaziantep FK", "Gaziantep", 52, "Gaziantep Stadium", 33502, "Turkey", "mid"),
    ("RIZ", "Rizespor", "Rizespor", 50, "Caykur Didi Stadium", 15332, "Turkey", "minnow"),
    ("ALN", "Alanyaspor", "Alanyaspor", 54, "Alanya Oba Stadium", 10842, "Turkey", "mid"),
    ("KAY", "Kayserispor", "Kayserispor", 52, "RHG Enerturk Stadium", 32864, "Turkey", "mid"),
    ("HAT", "Hatayspor", "Hatayspor", 48, "Mersin Stadium", 25497, "Turkey", "minnow"),
    ("SAM1", "Samsunspor", "Samsunspor", 54, "Samsun 19 Mayis Stadium", 33919, "Turkey", "trad"),
    ("EYU", "Eyupspor", "Eyupspor", 48, "Eyup Stadium", 2500, "Turkey", "minnow"),
    ("GOZ", "Goztepe", "Goztepe", 56, "Gursel Aksel Stadium", 20040, "Turkey", "trad"),
    ("BODR", "Bodrum FK", "Bodrum", 46, "Bodrum Ilce Stadium", 5000, "Turkey", "minnow"),
    ("ADN", "Adana Demirspor", "Adana Demirspor", 54, "Yeni Adana Stadium", 33543, "Turkey", "trad"),
    # ---- Argentina
    ("BOCA", "Boca Juniors", "Boca", 78, "La Bombonera", 54000, "Argentina", "elite"),
    ("RIV", "River Plate", "River", 79, "Monumental", 85018, "Argentina", "elite"),
    ("RAC1", "Racing Club", "Racing", 70, "El Cilindro", 51389, "Argentina", "trad"),
    ("IND", "Independiente", "Independiente", 70, "Libertadores de America", 52823, "Argentina", "trad"),
    ("SAL2", "San Lorenzo", "San Lorenzo", 68, "Pedro Bidegain", 39494, "Argentina", "trad"),
    ("VEL", "Velez Sarsfield", "Velez", 68, "Jose Amalfitani", 49540, "Argentina", "dev"),
    ("EST1A", "Estudiantes", "Estudiantes", 66, "Jorge Luis Hirschi", 32530, "Argentina", "dev"),
    ("NEW2", "Newell's Old Boys", "Newells", 64, "Marcelo Bielsa", 42000, "Argentina", "dev"),
    ("ROS1", "Rosario Central", "Rosario Central", 64, "Gigante de Arroyito", 48000, "Argentina", "trad"),
    ("TAL", "Talleres", "Talleres", 64, "Mario Alberto Kempes", 57000, "Argentina", "mid"),
    ("LAN", "Lanus", "Lanus", 62, "Ciudad de Lanus", 47090, "Argentina", "dev"),
    ("BAN", "Banfield", "Banfield", 58, "Florencio Sola", 34901, "Argentina", "mid"),
    ("HUR", "Huracan", "Huracan", 58, "Tomas Adolfo Duco", 48314, "Argentina", "trad"),
    ("ARG", "Argentinos Juniors", "Argentinos Jrs", 58, "Diego Armando Maradona", 25000, "Argentina", "dev"),
    ("DEF", "Defensa y Justicia", "Defensa", 56, "Norberto Tomaghello", 20000, "Argentina", "sell"),
    ("TIG", "Tigre", "Tigre", 54, "Jose Dellagiovanna", 26282, "Argentina", "mid"),
    ("PLAT", "Platense", "Platense", 48, "Ciudad de Vicente Lopez", 34530, "Argentina", "minnow"),
    ("INS", "Instituto", "Instituto", 50, "Juan Domingo Peron", 32000, "Argentina", "minnow"),
    ("CBB", "Belgrano", "Belgrano", 54, "Julio Cesar Villagra", 35000, "Argentina", "mid"),
    ("BARC", "Barracas Central", "Barracas", 46, "Claudio Tapia", 4400, "Argentina", "minnow"),
    # ---- Brazil
    ("FLA", "Flamengo", "Flamengo", 82, "Maracana", 78838, "Brazil", "elite"),
    ("PALM", "Palmeiras", "Palmeiras", 82, "Allianz Parque", 43713, "Brazil", "elite"),
    ("SAO", "Sao Paulo", "Sao Paulo", 78, "Morumbis", 72039, "Brazil", "trad"),
    ("COR1", "Corinthians", "Corinthians", 78, "Neo Quimica Arena", 49205, "Brazil", "trad"),
    ("FLU", "Fluminense", "Fluminense", 74, "Maracana", 78838, "Brazil", "trad"),
    ("BOTF", "Botafogo", "Botafogo", 76, "Nilton Santos", 46931, "Brazil", "dev"),
    ("ATM1", "Atletico Mineiro", "Atletico MG", 76, "Arena MRV", 46000, "Brazil", "trad"),
    ("GRE", "Gremio", "Gremio", 74, "Arena do Gremio", 55662, "Brazil", "trad"),
    ("INT1", "Internacional", "Internacional", 74, "Beira-Rio", 50842, "Brazil", "trad"),
    ("CRU", "Cruzeiro", "Cruzeiro", 74, "Mineirao", 62160, "Brazil", "trad"),
    ("VAS", "Vasco da Gama", "Vasco", 70, "Sao Januario", 21680, "Brazil", "trad"),
    ("SAN1", "Santos", "Santos", 70, "Vila Belmiro", 16068, "Brazil", "dev"),
    ("BHI", "Bahia", "Bahia", 66, "Arena Fonte Nova", 50025, "Brazil", "mid"),
    ("FOR1", "Fortaleza", "Fortaleza", 68, "Castelao", 63903, "Brazil", "mid"),
    ("CAP", "Athletico Paranaense", "Athletico PR", 68, "Ligga Arena", 42372, "Brazil", "dev"),
    ("RBB", "Red Bull Bragantino", "Bragantino", 62, "Nabi Abi Chedid", 15010, "Brazil", "dev"),
    ("CUI", "Cuiaba", "Cuiaba", 54, "Arena Pantanal", 44097, "Brazil", "minnow"),
    ("JUV1", "Juventude", "Juventude", 54, "Alfredo Jaconi", 19924, "Brazil", "minnow"),
    ("VIT1", "Vitoria", "Vitoria", 58, "Barradao", 35632, "Brazil", "trad"),
    # ---- USA: Major League Soccer
    ("MIA", "Inter Miami CF", "Inter Miami", 78, "DRV PNK Stadium", 25000, "USA", "ucl"),
    ("LAF", "Los Angeles FC", "LAFC", 75, "Banc of California Stadium", 22000, "USA", "ucl"),
    ("LAG", "LA Galaxy", "LA Galaxy", 74, "Dignity Health Sports Park", 22000, "USA", "ucl"),
    ("SEA", "Seattle Sounders FC", "Seattle", 74, "Lumen Field", 69000, "USA", "dev"),
    ("CIN", "FC Cincinnati", "Cincinnati", 71, "TQL Stadium", 26000, "USA", "dev"),
    ("NYC", "New York City FC", "NYCFC", 71, "Yankee Stadium", 62000, "USA", "dev"),
    ("NJN", "New York Red Bulls", "NY Red Bulls", 70, "Red Bull Arena", 25000, "USA", "mid"),
    ("ATL", "Atlanta United FC", "Atlanta", 70, "Mercedes-Benz Stadium", 71000, "USA", "dev"),
    ("MTL", "CF Montreal", "Montreal", 69, "Saputo Stadium", 19000, "USA", "mid"),
    ("PDX", "Portland Timbers", "Portland", 68, "Providence Park", 25000, "USA", "dev"),
    ("HOU", "Houston Dynamo FC", "Houston", 67, "Shell Energy Stadium", 20000, "USA", "mid"),
    ("CHI", "Chicago Fire FC", "Chicago", 67, "SeatGeek Stadium", 20000, "USA", "mid"),
    ("DAL", "FC Dallas", "Dallas", 66, "Toyota Stadium", 21000, "USA", "mid"),
    ("MIN", "Minnesota United FC", "Minnesota", 66, "Allianz Field", 30000, "USA", "mid"),
    ("RSL", "Real Salt Lake", "Salt Lake", 66, "America First Field", 30000, "USA", "mid"),
    ("KCL", "Colorado Rapids", "Colorado", 65, "Dicks Sporting Goods Park", 21000, "USA", "mid"),
    ("PHI", "Philadelphia Union", "Philadelphia", 65, "Subaru Park", 18000, "USA", "mid"),
    ("CMB", "Columbus Crew", "Columbus", 65, "Lower.com Field", 29000, "USA", "mid"),
    ("TORC", "Toronto FC", "Toronto", 67, "BMO Field", 30000, "USA", "dev"),
    ("VAN", "Vancouver Whitecaps FC", "Vancouver", 64, "BC Place", 54000, "USA", "mid"),
    ("ATX", "Austin FC", "Austin", 64, "Q2 Stadium", 20000, "USA", "dev"),
    ("SJC", "San Jose Earthquakes", "San Jose", 63, "PayPal Park", 18000, "USA", "minnow"),
    ("ORL", "Orlando City SC", "Orlando", 63, "Inter&Co Stadium", 25000, "USA", "minnow"),
    ("SBA", "St. Louis CITY SC", "St. Louis", 62, "Off the Levee", 15000, "USA", "minnow"),
    # ---- Saudi Arabia: Saudi Pro League
    ("HIL", "Al Hilal", "Al Hilal", 88, "Kingdom Arena", 32000, "Saudi Arabia", "elite"),
    ("NSR", "Al Nassr", "Al Nassr", 87, "Mrsool Park", 25000, "Saudi Arabia", "elite"),
    ("ITT", "Al Ittihad", "Al Ittihad", 82, "Prince Abdullah Al Faisal Stadium", 65000, "Saudi Arabia", "ucl"),
    ("AHL", "Al Ahli", "Al Ahli", 80, "ICC Stadium", 50000, "Saudi Arabia", "ucl"),
    ("SHB", "Al Shabab", "Al Shabab", 76, "Prince Faisal bin Fahd Stadium", 19000, "Saudi Arabia", "ucl"),
    ("ETT", "Al Ettifaq", "Al Ettifaq", 74, "King Abdullah Sports City", 62000, "Saudi Arabia", "dev"),
    ("TAW", "Al Taawoun", "Al Taawoun", 70, "King Abdullah II Stadium", 15000, "Saudi Arabia", "mid"),
    ("FAY", "Al Fateh", "Al Fateh", 68, "Abdullah Al Fateh Stadium", 30000, "Saudi Arabia", "mid"),
    ("RYD", "Al Riyadh", "Al Riyadh", 68, "Prince Abdullah Al Faisal Stadium", 65000, "Saudi Arabia", "mid"),
    ("DHU", "Al Duhail", "Al Duhail", 67, "Prince Sultan bin Jabir Stadium", 14000, "Saudi Arabia", "mid"),
    ("AKH", "Al Khobar", "Al Khobar", 66, "Prince Mohammed bin Fahd Stadium", 30000, "Saudi Arabia", "mid"),
    ("WHD", "Al Wehda", "Al Wehda", 66, "Prince Abdullah Al Jawahir Stadium", 16000, "Saudi Arabia", "mid"),
    ("DMA", "Damac FC", "Damac", 65, "Prince Mitab bin Abdullah Stadium", 20000, "Saudi Arabia", "mid"),
    ("OKD", "Al Okhdood", "Al Okhdood", 62, "King Abdulaziz Stadium", 25000, "Saudi Arabia", "minnow"),
    ("HAZ", "Al Hazem", "Al Hazem", 62, "Prince Abdulaziz bin Murakhi Stadium", 15000, "Saudi Arabia", "minnow"),
    ("DRY", "Al Diriyah", "Al Diriyah", 60, "King Khalid Stadium", 25000, "Saudi Arabia", "minnow"),
    ("FTH", "Al Khaleej", "Al Khaleej", 60, "Al Khaleej Club Stadium", 15000, "Saudi Arabia", "minnow"),
    ("RAE", "Al Raed", "Al Raed", 59, "Prince Abdulaziz Stadium", 15000, "Saudi Arabia", "minnow"),
]

# hand-seeded recognisable stars: (code, name, nat, age, pos, pos2, CA, PA, foot, wage/wk, value m)
STARS = [
    ("RMA", "Kylian Mbappe", "France", 27, "ST", "AML", 19, 20, "R", 1.2, 220),
    ("RMA", "Jude Bellingham", "England", 23, "AMC", "MC", 18, 20, "R", 0.9, 180),
    ("RMA", "Vinicius Junior", "Brazil", 26, "AML", "ST", 18, 19, "R", 0.9, 170),
    ("RMA", "Federico Valverde", "Uruguay", 28, "MC", "DM", 18, 18, "R", 0.6, 120),
    ("RMA", "Thibaut Courtois", "Belgium", 34, "GK", "", 17, 17, "L", 0.5, 25),
    ("RMA", "Aurelien Tchouameni", "France", 26, "DM", "DC", 17, 18, "R", 0.5, 90),
    ("RMA", "Eduardo Camavinga", "France", 23, "MC", "DL", 16, 18, "L", 0.4, 80),
    ("RMA", "Rodrygo", "Brazil", 25, "AMR", "AML", 17, 18, "L", 0.5, 100),
    ("BAR", "Lamine Yamal", "Spain", 19, "AMR", "ST", 18, 20, "L", 0.5, 200),
    ("BAR", "Pedri", "Spain", 23, "MC", "AMC", 18, 19, "R", 0.5, 130),
    ("BAR", "Raphinha", "Brazil", 29, "AML", "AMR", 17, 17, "L", 0.4, 70),
    ("BAR", "Frenkie de Jong", "Netherlands", 29, "MC", "DM", 16, 16, "R", 0.4, 45),
    ("BAR", "Robert Lewandowski", "Poland", 38, "ST", "", 16, 16, "R", 0.4, 15),
    ("BAR", "Gavi", "Spain", 22, "MC", "AMC", 16, 18, "R", 0.3, 90),
    ("MCI", "Erling Haaland", "Norway", 26, "ST", "", 19, 20, "L", 0.9, 200),
    ("MCI", "Phil Foden", "England", 26, "AMC", "AMR", 18, 19, "L", 0.5, 120),
    ("MCI", "Rodri", "Spain", 30, "DM", "MC", 18, 18, "R", 0.5, 90),
    ("MCI", "Ruben Dias", "Portugal", 29, "DC", "", 17, 17, "R", 0.4, 70),
    ("MCI", "Bernardo Silva", "Portugal", 32, "MC", "AMR", 16, 16, "L", 0.35, 40),
    ("LIV", "Mohamed Salah", "Egypt", 34, "AMR", "ST", 18, 18, "L", 0.6, 55),
    ("LIV", "Virgil van Dijk", "Netherlands", 35, "DC", "", 17, 17, "R", 0.45, 28),
    ("LIV", "Alexis Mac Allister", "Argentina", 27, "MC", "DM", 17, 17, "R", 0.3, 80),
    ("LIV", "Dominik Szoboszlai", "Hungary", 25, "MC", "AMC", 16, 18, "R", 0.25, 75),
    ("LIV", "Alisson Becker", "Brazil", 33, "GK", "", 18, 18, "R", 0.4, 40),
    ("LIV", "Florian Wirtz", "Germany", 23, "AMC", "AML", 18, 20, "R", 0.45, 150),
    ("ARS", "Bukayo Saka", "England", 24, "AMR", "AML", 18, 19, "L", 0.4, 130),
    ("ARS", "Martin Odegaard", "Norway", 27, "AMC", "MC", 18, 18, "L", 0.4, 110),
    ("ARS", "Declan Rice", "England", 27, "DM", "MC", 18, 18, "R", 0.35, 110),
    ("ARS", "William Saliba", "France", 25, "DC", "", 18, 19, "R", 0.3, 100),
    ("ARS", "Gabriel Magalhaes", "Brazil", 28, "DC", "", 17, 17, "L", 0.25, 75),
    ("ARS", "David Raya", "Spain", 30, "GK", "", 17, 17, "R", 0.2, 40),
    ("MUN", "Bruno Fernandes", "Portugal", 31, "AMC", "MC", 17, 17, "R", 0.35, 55),
    ("CHE", "Enzo Fernandez", "Argentina", 25, "MC", "DM", 17, 18, "R", 0.3, 95),
    ("CHE", "Cole Palmer", "England", 24, "AMC", "AMR", 18, 19, "L", 0.3, 130),
    ("BAY", "Harry Kane", "England", 33, "ST", "AMC", 19, 19, "R", 0.6, 90),
    ("BAY", "Joshua Kimmich", "Germany", 31, "DM", "DR", 17, 17, "R", 0.4, 40),
    ("BAY", "Jamal Musiala", "Germany", 23, "AMC", "AML", 18, 20, "R", 0.4, 150),
    ("BAY", "Manuel Neuer", "Germany", 40, "GK", "", 16, 16, "R", 0.3, 5),
    ("BVB", "Julian Brandt", "Germany", 30, "AMC", "AMR", 16, 16, "R", 0.2, 35),
    ("PSG", "Ousmane Dembele", "France", 29, "AMR", "ST", 18, 18, "L", 0.6, 110),
    ("PSG", "Achraf Hakimi", "Morocco", 27, "DR", "AMR", 18, 18, "R", 0.4, 90),
    ("PSG", "Vitinha", "Portugal", 26, "MC", "DM", 17, 18, "R", 0.3, 90),
    ("INT", "Lautaro Martinez", "Argentina", 29, "ST", "", 18, 18, "R", 0.3, 95),
    ("INT", "Nicolo Barella", "Italy", 29, "MC", "", 17, 17, "R", 0.25, 75),
    ("JUV", "Dusan Vlahovic", "Serbia", 26, "ST", "", 16, 17, "R", 0.25, 60),
    ("MIL", "Rafael Leao", "Portugal", 27, "AML", "ST", 17, 17, "R", 0.25, 75),
    ("ATM", "Antoine Griezmann", "France", 35, "AMC", "ST", 16, 16, "L", 0.3, 20),
    ("ATM", "Jan Oblak", "Slovenia", 33, "GK", "", 17, 17, "R", 0.25, 30),
    ("NAP", "Kevin De Bruyne", "Belgium", 35, "AMC", "MC", 17, 17, "R", 0.35, 25),
    ("AJA1", "Steven Berghuis", "Netherlands", 34, "AMR", "AMC", 14, 14, "L", 0.06, 6),
    ("SLB", "Angel Di Maria", "Argentina", 38, "AMR", "AMC", 15, 15, "L", 0.08, 5),
    ("FCP", "Pepe Reina", "Spain", 43, "GK", "", 12, 12, "R", 0.02, 0.2),
    ("CEL", "Kasper Schmeichel", "Denmark", 39, "GK", "", 14, 14, "R", 0.05, 3),
    ("WXC", "Nathan Broadhead", "Wales", 27, "ST", "AMR", 12, 13, "R", 0.03, 3),
    ("RIV", "Franco Mastantuono", "Argentina", 19, "AMC", "AMR", 14, 18, "L", 0.03, 25),
    ("FLA", "Giorgian de Arrascaeta", "Uruguay", 32, "AMC", "AML", 15, 15, "R", 0.08, 12),
    ("TOT", "Son Heung-min", "South Korea", 34, "AML", "ST", 16, 16, "R", 0.3, 25),
    ("NEW", "Bruno Guimaraes", "Brazil", 28, "MC", "DM", 17, 17, "R", 0.2, 80),
    ("NEW", "Alexander Isak", "Sweden", 26, "ST", "", 18, 18, "R", 0.3, 120),
    ("LEI", "Jamie Vardy", "England", 39, "ST", "", 13, 13, "R", 0.04, 1),
    ("EVE", "Jordan Pickford", "England", 32, "GK", "", 16, 16, "L", 0.15, 28),
    ("CRY", "Eberechi Eze", "England", 28, "AMC", "AML", 16, 17, "R", 0.15, 60),
    ("BRI", "Kaoru Mitoma", "Japan", 29, "AML", "AMC", 16, 16, "R", 0.12, 55),
]

# Realistic rivalries and derbies - prevents unrealistic transfers and adds hype
RIVALRIES = {
    # England - Premier League
    "MCI": ["MUN", "LIV", "ARS"],  # City vs United, Liverpool, Arsenal
    "MUN": ["MCI", "LIV", "LEE", "ARS"],  # United vs City, Liverpool, Leeds, Arsenal
    "LIV": ["MUN", "MCI", "EVE"],  # Liverpool vs United, City, Everton
    "ARS": ["TOT", "CHE", "MUN"],  # Arsenal vs Tottenham, Chelsea, United
    "TOT": ["ARS", "CHE", "WHU"],  # Tottenham vs Arsenal, Chelsea, West Ham
    "CHE": ["ARS", "TOT", "FUL"],  # Chelsea vs Arsenal, Tottenham, Fulham
    "EVE": ["LIV"],  # Everton vs Liverpool
    "WHU": ["TOT", "MIL"],  # West Ham vs Tottenham, Millwall
    "NEW": ["SUN"],  # Newcastle vs Sunderland
    "AVL": ["BIR", "WBA"],  # Villa vs Birmingham, West Brom
    "BRI": ["CRY"],  # Brighton vs Palace
    "FUL": ["CHE", "QPR", "BRE"],  # Fulham vs Chelsea, QPR, Brentford
    "WOL": ["WBA", "AVL"],  # Wolves vs West Brom, Villa
    "NOT": ["DER", "LEI"],  # Forest vs Derby, Leicester
    "LEI": ["COV", "DER", "NOT"],  # Leicester vs Coventry, Derby, Forest
    # Spain
    "RMA": ["BAR", "ATM"],  # Real vs Barca, Atleti
    "BAR": ["RMA", "ESP"],  # Barca vs Real, Espanyol
    "ATM": ["RMA", "SEV"],  # Atleti vs Real, Sevilla
    "SEV": ["BET"],  # Sevilla vs Betis
    "BET": ["SEV"],  # Betis vs Sevilla
    "VAL": ["LEV"],  # Valencia vs Levante
    # Italy
    "INT": ["ACM", "JUV"],  # Inter vs Milan, Juve
    "ACM": ["INT", "JUV"],  # Milan vs Inter, Juve
    "JUV": ["INT", "ACM", "TOR"],  # Juve vs Inter, Milan, Torino
    "ROM": ["LAZ"],  # Roma vs Lazio
    "LAZ": ["ROM"],  # Lazio vs Roma
    "NAP": ["ROM"],  # Napoli vs Roma
    # Germany
    "BAY": ["BVB", "M60"],  # Bayern vs Dortmund, 1860
    "BVB": ["BAY", "SCH"],  # Dortmund vs Bayern, Schalke
    "SCH": ["BVB", "DUS"],  # Schalke vs Dortmund, Dusseldorf
    # France
    "PSG": ["OM", "OL"],  # PSG vs Marseille, Lyon
    "OM": ["PSG", "OL"],  # Marseille vs PSG, Lyon
    "OL": ["ASSE", "OM"],  # Lyon vs Saint-Etienne, Marseille
    # Scotland
    "CEL": ["RAN"],  # Celtic vs Rangers
    "RAN": ["CEL"],  # Rangers vs Celtic
    # etc.
}

# Derby names for hype
DERBY_NAMES = {
    ("MCI", "MUN"): "Manchester Derby",
    ("MUN", "MCI"): "Manchester Derby",
    ("LIV", "EVE"): "Merseyside Derby",
    ("EVE", "LIV"): "Merseyside Derby",
    ("ARS", "TOT"): "North London Derby",
    ("TOT", "ARS"): "North London Derby",
    ("CHE", "ARS"): "London Derby",
    ("ARS", "CHE"): "London Derby",
    ("CHE", "TOT"): "London Derby",
    ("TOT", "CHE"): "London Derby",
    ("RMA", "BAR"): "El Clásico",
    ("BAR", "RMA"): "El Clásico",
    ("RMA", "ATM"): "Madrid Derby",
    ("ATM", "RMA"): "Madrid Derby",
    ("SEV", "BET"): "Seville Derby",
    ("BET", "SEV"): "Seville Derby",
    ("INT", "ACM"): "Derby della Madonnina",
    ("ACM", "INT"): "Derby della Madonnina",
    ("ROM", "LAZ"): "Derby della Capitale",
    ("LAZ", "ROM"): "Derby della Capitale",
    ("JUV", "TOR"): "Derby della Mole",
    ("TOR", "JUV"): "Derby della Mole",
    ("BAY", "BVB"): "Der Klassiker",
    ("BVB", "BAY"): "Der Klassiker",
    ("CEL", "RAN"): "Old Firm",
    ("RAN", "CEL"): "Old Firm",
    ("BOCA", "RIV"): "Superclásico",
    ("RIV", "BOCA"): "Superclásico",
    ("PSG", "OM"): "Le Classique",
    ("OM", "PSG"): "Le Classique",
}

# Elite clubs that should dominate - prevents Fulham topping PL
ELITE_CLUBS = ["MCI", "ARS", "LIV", "RMA", "BAR", "BAY", "PSG", "INT", "JUV", "ACM", "BVB", "CHE", "MUN"]
TOP_CLUBS = ["MCI", "ARS", "LIV", "CHE", "MUN", "TOT", "NEW", "AVL", "RMA", "BAR", "ATM", "BAY", "BVB", "LEV1", "PSG", "OM", "INT", "JUV", "ACM", "NAP"]

# national name pools: first / last
NATIONS = {
    "England": 400, "Spain": 260, "France": 260, "Germany": 220, "Italy": 220,
    "Portugal": 180, "Netherlands": 170, "Brazil": 240, "Argentina": 220,
    "Belgium": 130, "Scotland": 120, "Turkey": 140, "Wales": 60, "Denmark": 90,
    "Norway": 70, "Sweden": 90, "Poland": 90, "Croatia": 70, "Serbia": 70,
    "Uruguay": 70, "Colombia": 90, "Mexico": 80, "USA": 120, "Japan": 90,
    "South Korea": 70, "Nigeria": 110, "Ghana": 80, "Senegal": 70,
    "Ivory Coast": 60, "Morocco": 80, "Algeria": 60, "Egypt": 60, "Cameroon": 60,
    "Ireland": 60, "Switzerland": 60, "Austria": 60, "Czechia": 60,
    "Ukraine": 60, "Greece": 60, "Chile": 60, "Ecuador": 60, "Paraguay": 40,
    "Australia": 60, "Canada": 60, "Slovakia": 40, "Hungary": 50, "Romania": 50,
    "Bosnia": 40, "Mali": 40, "DR Congo": 40, "Guinea": 30, "Burkina Faso": 30,
    "Slovenia": 30, "Finland": 30, "Iceland": 25, "Israel": 30, "Tunisia": 30,
    "Saudi Arabia": 30, "Qatar": 20, "South Africa": 40, "Jamaica": 30,
    "Peru": 40, "Venezuela": 40, "Costa Rica": 25, "Albania": 30, "Kosovo": 30,
    "Georgia": 30, "Armenia": 20, "North Macedonia": 25, "Montenegro": 20,
    "Northern Ireland": 25, "Bulgaria": 40, "Cyprus": 25, "Kazakhstan": 25,
    "Iran": 30, "Uzbekistan": 20, "New Zealand": 20, "Cape Verde": 15,
    "Haiti": 15, "Honduras": 20, "Bolivia": 20, "Panama": 20, "Curacao": 15,
    "Angola": 25, "Zambia": 25, "Kenya": 20, "Uganda": 20, "Equatorial Guinea": 15,
    "Gambia": 20, "Sierra Leone": 15, "Togo": 15, "Benin": 15, "Gabon": 15,
    "Liberia": 10, "Comoros": 10, "Madagascar": 15, "Luxembourg": 15,
    "Faroe Islands": 10, "Estonia": 20, "Latvia": 20, "Lithuania": 20,
    "Belarus": 20, "Moldova": 15, "Azerbaijan": 20, "Andorra": 10,
    "San Marino": 10, "Liechtenstein": 10, "Malta": 15, "Gibraltar": 10,
    "Trinidad & Tobago": 15, "Suriname": 15, "Guinea-Bissau": 15, "Mauritania": 10,
    "Libya": 10, "Iraq": 15, "Jordan": 10, "Syria": 10, "Palestine": 10,
    "Thailand": 15, "Vietnam": 15, "Indonesia": 15, "India": 20, "China PR": 15,
    "El Salvador": 10, "Guatemala": 10, "Nicaragua": 10, "Dominican Republic": 15,
    "Puerto Rico": 10, "Martinique": 10, "Guadeloupe": 10, "French Guiana": 10,
    "DR Congo B": 10, "Namibia": 10, "Botswana": 10, "Zimbabwe": 15,
    "Mozambique": 10, "Tanzania": 10, "Rwanda": 10, "Sudan": 10, "Chad": 10,
}
