"""Procedural name generation by nationality."""

FIRST = {
"England": "Harry Jack Oliver George Charlie Thomas Alfie Freddie Leo Archie Oscar Henry William Edward Freddie Callum Ryan Lewis Mason Joshua Kyle Liam Daniel Sam Joe Adam Ryan Elliot Connor Tyler Nathan Harvey Jacob Ethan Kai Reece Marcus Ben Callum Jordan Declan Jude Cole Ruben Tammy Ivan Troy Andre",
"Spain": "Sergio Daniel Alejandro Pablo Javier Adrian Alvaro Rodrigo Marcos Ivan Hugo Mario Diego Victor Oscar Raul Jose Miguel Angel Carlos Francisco Manuel Juan Antonio Pedro Luis Fernando Rafael Alberto Iker Unai Mikel Ander Gavi Pedri Ferran Nico Pau Eric Aleix Raul Borja Joselu Aitor Gaizka Inaki",
"France": "Antoine Lucas Julien Clement Theo Hugo Kylian Marcus Adrien Moussa Ousmane Alexandre Raphael Florian Wesley Romain Yassin Nabil Karim Ibrahim Sekou Amadou Boubacar Malang Warren Rayan Enzo Matteo Mathis Nolan Baptiste Valentin Quentin Geoffrey Loic Allan Steve",
"Germany": "Lukas Jonas Felix Maximilian Paul Leon Tim Florian Nico Marcel Kevin Julian Pascal Dennis Marvin Philipp Fabian Sebastian Tobias Markus Matthias Daniel Christopher Andre Jan Niklas Kai Lennart Erik Moritz Joshua Luca Gian Luca",
"Italy": "Marco Alessandro Andrea Lorenzo Matteo Francesco Davide Giuseppe Antonio Luca Simone Federico Gianluca Nicolo Riccardo Stefano Daniele Christian Andrea Pietro Tommaso Filippo Samuele Emanuele Mattia Alessio Gabriele Vincenzo Salvatore",
"Portugal": "Joao Rui Pedro Tiago Bruno Miguel Nuno Andre Fabio Ricardo Sergio Paulo Hugo Daniel Carlos Jose Goncalo Bernardo Rafael Diogo Tomas Francisco Martim Afonso Renato Ruben Nelson Cristiano Vitor Domingos",
"Netherlands": "Daan Sem Milan Levi Luuk Bram Thijs Wout Matthijs Stefan Jasper Robin Kevin Danny Jordy Sven Lars Ruben Cody Ryan Donny Kenneth Teun Bart Joost Quinten Xavi Fer Dony Brian",
"Brazil": "Lucas Gabriel Matheus Pedro Henrique Rafael Bruno Felipe Vinicius Rodrygo Endrick Estevao Kaio Luan Everton Thiago Wesley Igor Anderson Douglas Marcelo Alexandre Danilo Emerson Renan Caio Savio Talles",
"Argentina": "Lionel Julian Lautaro Enzo Mateo Thiago Franco Nicolas Cristian Angel Rodrigo Emiliano Alejandro Paulo Giovani Exequiel Marcos Valentin Tomas Facundo Joaquin Santiago Leandro Damian Alexis Bruno Ignacio",
"Belgium": "Kevin Romelu Youri Dries Thibaut Eden Axel Leandro Jérémy Michy Yannick Wout Zeno Amadou Nathan Hugo Loïs Arthur Senne Maxim Debast Olivier Aster Charly Cyriel",
"Scotland": "Scott Lewis Callum Ryan Andrew Grant Stuart Craig Liam Billy Jack Connor Ross Kyle Ben Nathan John Fraser Declan Kieran Lennon Aaron Jamie Ewan Murray Cammy",
"Turkey": "Emre Arda Kerem Yunus Baris Can Mert Umut Ozan Yusuf Hakan Cengiz Irfan Abdulkadir Orkun Ferdi Samet Ahmet Halil Bertug Kenan Muhammed",
"Wales": "Gareth Aaron Harry Ben David Daniel Ethan Owen Rhys Tyler Kieran Lloyd Ioan Cai Ellis Tomos Iwan Dafydd Ryan Nathan",
"Denmark": "Christian Andreas Mikkel Rasmus Pierre-Emile Jonas Viktor Mathias Oliver Kasper Frederik Nicolai Morten Jesper Lucas Emil",
"Norway": "Erling Martin Ode Sander Andreas Kristoffer Ola Markus Vetle Leo Nicolai Hakon Jonas Sondre",
"Sweden": "Emil Viktor Isak Alexander Dejan Anthony Yasin Kenan Jesper Mattias Albin Filip Elanga Robin Pontus",
"Poland": "Piotr Robert Jakub Kamil Mateusz Sebastian Szymon Krzysztof Nicola Bartosz Damian Michal Karol Patryk Adam",
"Croatia": "Luka Mateo Josip Ivan Andrej Martin Nikola Petar Dominik Dario Borna Mario Ante Marko Duje",
"Serbia": "Dusan Sergej Filip Aleksandar Luka Strahinja Nemanja Andrija Veljko Lazar Marko Stefan Uros",
"Uruguay": "Federico Rodrigo Nicolas Maximiliano Darwin Facundo Matias Agustin Giorgian Jose Ronald Nahitan Manuel",
"Colombia": "Luis James Juan Jhon Jefferson Richard Yerry Davinson Daniel Jorge Mateo Yaser Kevin",
"Mexico": "Hirving Raul Edson Santiago Jorge Alexis Cesar Erick Guillermo Santiago Diego Orlando Santiago",
"USA": "Christian Gio Weston Folarin Tim Malik Yunus Ricardo Mark Tyler Tanner Kevin Diego Alejandro",
"Japan": "Kaoru Takefusa Wataru Daichi Junya Ayase Kyogo Ritsu Takumi Ko Itakura Hiroki Daizen Shogo",
"South Korea": "Son Lee Kim Park Hwang Cho Jung Han Seol Kang Baek Yang Min-jae In-beom",
"Nigeria": "Victor Ademola Samuel Chidera Bright Alex Wilfred Taiwo Kelechi Calvin Moses Toluwalase Olamide",
"Ghana": "Mohammed Kudus Antoine Thomas Kamaldeen Inaki Jordan Osamuel Daniel Afriyie Gideon",
"Senegal": "Sadio Ismaila Iliman Pape Boulaye Lamine Habib Cheikh Mamadou Kalidou Ousseynou",
"Ivory Coast": "Franck Sebastien Simon Amad Wilfried Jean-Michael Ibrahim Ghislain Oumar Max-Alain",
"Morocco": "Achraf Hakim Brahim Sofyan Azzedine Nayef Youssef Bilal Anass Chadi Amine Ismael",
"Algeria": "Riyad Ismael Houssem Amine Mohamed Yacine Ramy Nabil Said Billel",
"Egypt": "Mohamed Salah Omar Marmoush Mostafa Trezeguet Ahmed Mohamed Elneny Emam Ashour",
"Cameroon": "Andre Bryan Carlos Vincent Eric Maxim Choupo Karl Toko Clinton Njie",
"Ireland": "Caoimhin Evan Nathan Shane Adam James Darragh Finn Festy Ebosele Liam Scales",
"Switzerland": "Granit Xherdan Breel Remo Nico Manuel Dan Ruben Fabian Michel Aebischer",
"Austria": "David Marcel Konrad Christoph Marko Patrick Florian Romano Michael Kevin",
"Czechia": "Patrik Tomas Antonin Adam Ondrej Ladislav Vladimir Jan Matej Jurasek",
"Ukraine": "Andriy Oleksandr Mykhailo Ruslan Viktor Heorhiy Artem Illya Danylo",
"Greece": "Vangelis Kostas Giorgos Tasos Dimitris Fotis Christos Anastasios Sotiris",
"Chile": "Alexis Arturo Eduardo Ben Brereton Guillermo Marcelino Vicente Dario",
"Ecuador": "Moises Piero Pervis Kendry Joel Estupinan Gonzalo Plata Nilson Angulo",
"Paraguay": "Miguel Julio Ramon Antonio Miguel Angel Derlis Diego Antonio Sanabria",
"Australia": "Mathew Aziz Jackson Bailey Mitchell Jordan Connor Harry Awer Mabil",
"Canada": "Alphonso Jonathan Cyle Tajon Stephen Ismael Tani Oluwaseyi Richie Laryea",
"Slovakia": "Milan Stanislav Tomas David Ondrej Laszlo Robert Ivan Norbert",
"Hungary": "Dominik Milos Roland Willi Orban Andras Szabolcs Bendeguz Callum",
"Romania": "Ianis Nicolae Dennis Razvan Andrei Alexandru Olimpiu Valentin",
"Bosnia": "Edin Miralem Sead Ermedin Amar Rade Anel Ahmedin Nikola",
"Mali": "Yves Amadou Moussa Djene Mohamed Kamory Lassana Sekou Boubacar",
"DR Congo": "Chancel Yoane Silas Bakambu Arthur Nathanael Samuel Meschack Gaetan",
"Guinea": "Naby Serhou Julian Ilaix Aguibou Francois Morgan Facinet",
"Burkina Faso": "Bertrand Edmond Dango Gustavo Cyrille Issa Yssouf Lassina",
"Slovenia": "Jan Benjamin Josip Petar Adam Sandi David Nino Miha",
"Finland": "Teemu Glen Lukas Robin Fredrik Anssi Robert Otso Kaan",
"Iceland": "Alfreo Jon Dagur Hakon Arnor Sveinn Mikael Andri",
"Israel": "Manor Eran Liel Shon Oscar Dor Shon Weissman Ilay",
"Tunisia": "Youssef Hannibal Wajdi Ellyes Aissa Naim Ferjani",
"Saudi Arabia": "Salem Firas Mohammed Abdullah Saleh Hassan Ali",
"Qatar": "Akram Almoez Hassan Homam Boualem Pedro Miguel",
"South Africa": "Percy Teboho Evidence Lyle Ronwen Bongokuhle Themba",
"Jamaica": "Leon Michail Antonio Demarai Ethan Shamar Dexter",
"Peru": "Gianluca Edison Andre Renato Yoshimar Luis Miguel",
"Venezuela": "Yeferson Salomon Darwin Jon Josef Telasco Cristian",
"Costa Rica": "Keylor Joel Manfred Warren Alonso Brandon Anthony",
"Albania": "Armando Nedim Kristjan Thomas Medon Berat Arber",
"Kosovo": "Vedat Milot Edon Blend Lirim Arijanet Fisnik",
"Georgia": "Khvicha Giorgi Otar Zuriko Saba Luka Anzor",
"Armenia": "Henrikh Lucas Eduard Vahan Nair Tigran",
"North Macedonia": "Eljif Enis Bojan Darko Aleksandar Milan",
"Montenegro": "Stevan Nikola Marko Adam Ognjen Milos",
"Northern Ireland": "Conor Paddy Shea Daniel Alfie Jamal Ethan",
"Bulgaria": "Kiril Ilian Filip Martin Anton Georgi",
"Cyprus": "Grigoris Ioannis Marinos Minas Stelios",
"Kazakhstan": "Bakhtiyar Islambek Yan Artyom Nuraly",
"Iran": "Mehdi Sardar Alireza Saeid Amir",
"Uzbekistan": "Abbosbek Eldor Jaloliddin Khusayin",
"New Zealand": "Chris Liberato Sarpreet Matthew Alex",
"Cape Verde": "Ryan Bebe Garry Kenny Kevin",
"Haiti": "Duckens Frantz Bryan Wilde-Donald",
"Honduras": "Alberth Luis Jonathan Anthony",
"Bolivia": "Miguel Jaume Ramiro Vaca Moises",
"Panama": "Jose Luis Cecilio Adalberto Eric",
"Curacao": "Juninho Leandro Kenji Roly",
"Angola": "Mbala Zini Felicio Milson Freddy",
"Zambia": "Patson Fashion Evans Lubambo",
"Kenya": "Michael Joseph Anthony Richard",
"Uganda": "Travis Allan Bevis Rogers",
"Equatorial Guinea": "Emilio Nsue Ivan Salvador Luis",
"Gambia": "Ablie Yankuba Musa Adama Ebrima",
"Sierra Leone": "Alhaji Kei Augustus Sullay",
"Togo": "Ihlas Peniel Floyd Kossi",
"Benin": "Steve Jodel Olaitan Cedric",
"Gabon": "Pierre-Emerick Denis Mario Lemina",
"Liberia": "George Timothy Murphy William",
"Comoros": "El Fardou Rafidine Faiz",
"Madagascar": "Carolus Hakim Njiva",
"Luxembourg": "Gerson Leandro Vincent Chris",
"Faroe Islands": "Brandur Hallur Klaemint",
"Estonia": "Sergei Konstantin Mattias Vlasiy",
"Latvia": "Janis Vladimirs Anton Roberts",
"Lithuania": "Arvydas Fedor Giedrius Edgaras",
"Belarus": "Anton Kirill Denis Ivan",
"Moldova": "Vitalie Artur Nicolae Vadim",
"Azerbaijan": "Emin Mahir Rufat Renat",
"Andorra": "Marc Ildefons Jordi Max",
"San Marino": "Matteo Nicola Alessandro",
"Liechtenstein": "Noah Fabio Nicolas",
"Malta": "Paul Joseph Matthew Kyrian",
"Gibraltar": "Reece Jay Liam Kian",
"Trinidad & Tobago": "Levi Ajani Andre Nathaniel",
"Suriname": "Tyrone Gleofilo Myenty Ryan",
"Guinea-Bissau": "Beto Ze Turbo Mama",
"Mauritania": "Aboubakar Hemeya Idrissa",
"Libya": "Faisal Mohamed Hamdou",
"Iraq": "Aymen Zidane Iqbal Mohanad",
"Jordan": "Mousa Ali Yazan",
"Syria": "Omar Mahmoud Pablo",
"Palestine": "Oday Wesam Mohammed",
"Thailand": "Chanathip Supachai Teerasil",
"Vietnam": "Nguyen Quang Hai Doan",
"Indonesia": "Marselino Egy Rizky",
"India": "Sunil Sandesh Anirudh",
"China PR": "Wu Lei Zhang Yuning",
"El Salvador": "Darwin Nelson Brayan",
"Guatemala": "Rubio Oscar Nicholas",
"Nicaragua": "Juan Matias Jaime",
"Dominican Republic": "Mariano Heinz Edison",
"Puerto Rico": "Gerald Jeremy Nicolas",
"Martinique": "Kevin Jonathan Jordy",
"Guadeloupe": "Thomas Matthias Dimitri",
"French Guiana": "Ludovic Loic Marvin",
"Namibia": "Peter Deon Absalom",
"Botswana": "Thato Kabelo Thatayaone",
"Zimbabwe": "Marvelous Knowledge Tino",
"Mozambique": "Edson Geny Reinildo",
"Tanzania": "Mbwana Simon Faridi",
"Rwanda": "Hakim Olivier Yannick",
"Sudan": "Mohamed Yousif Ramadan",
"Chad": "Ezechiel Marius Placide",
}

LAST = {
"England": "Smith Jones Taylor Brown Williams Wilson Johnson Davies Robinson Wright Thompson Evans Walker White Roberts Green Hall Wood Clarke Harris Lewis Scott King Baker Turner Phillips Mitchell Carter Adams Richardson Cook Morgan Bell Bailey Parker Cooper Ward Morris Murphy Rogers Price Sanders Clarke Stewart Turner Phillips Campbell Edwards Hughes O'Connor Doyle",
"Spain": "Garcia Martinez Lopez Sanchez Perez Gomez Fernandez Gonzalez Rodriguez Martin Jimenez Ruiz Hernandez Diaz Moreno Alvarez Romero Navarro Torres Dominguez Vazquez Ramos Gil Serrano Blanco Molina Morales Ortega Castro Ortiz Rubio Marin Sanz Iglesias Medina Garrido Cortes Castillo Santos Lozano Guerrero Cano Prieto Mendez Cruz Calvo Gallego Vidal Herrera Leon Ibanez Nunez Nieto Aguilar Santana",
"France": "Martin Bernard Dubois Thomas Robert Petit Durand Leroy Moreau Simon Laurent Lefebvre Michel Garcia David Bertrand Roux Vincent Fournier Girard Andre Lefevre Mercier Blanc Guerin Muller Henry Roussel Nicolas Perrin Morin Mathieu Clement Gauthier Dumont Lopez Fontaine Chevalier Robin Masson Sanchez Gerard Nguyen Boyer Denis Lemaire Duval Joly Gaillard",
"Germany": "Muller Schmidt Schneider Fischer Weber Meyer Wagner Becker Schulz Hoffmann Schafer Koch Bauer Richter Klein Wolf Schroder Neumann Schwarz Zimmermann Braun Kruger Hofmann Hartmann Lange Schmitt Werner Krause Lehmann Kohler Herrmann Konig Walter Peters Lang Scholz Moller Weiss Jung Hahn Schubert Vogel Friedrich Keller Gunther Frank Berger Winkler Roth Beck Lorenz",
"Italy": "Rossi Russo Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti De Luca Mancini Costa Giordano Rizzo Lombardi Moretti Barbato Villa Fabbri Rossetti Fontana Mariani Rinaldi Caruso Ferrari Leone Longo Gatti Martini Sala Vitale De Santis Grassi Pellegrini Serra Coppola Amato Parisi Ferri",
"Portugal": "Silva Santos Ferreira Pereira Oliveira Costa Rodrigues Martins Jesus Sousa Fernandes Goncalves Gomes Lopes Marques Alves Almeida Ribeiro Pinto Carvalho Teixeira Moreira Correia Mendes Nunes Cardoso Monteiro Rocha Vieira Barbosa Tavares Pires Figueiredo Neves Sequeira",
"Netherlands": "de Jong Jansen de Vries van den Berg Bakker Visser Smit Meijer de Boer Mulder de Groot Bosch Vos Peters Hendriks van Dijk Dekker Brouwer de Wit Dijkstra Smits van der Meer van Leeuwen Vermeulen Willems van Vliet de Koning Kuiper Schouten Hoekstra Dijkman Zandbergen",
"Brazil": "Silva Santos Oliveira Souza Pereira Costa Rodrigues Almeida Nascimento Lima Araujo Fernandes Carvalho Gomes Martins Rocha Ribeiro Alves Barbosa Cardoso Teixeira Cavalcante Dias Moreira Nogueira Pinto Peixoto Campos Farias Tavares Batista",
"Argentina": "Gonzalez Rodriguez Gomez Fernandez Lopez Martinez Diaz Perez Sanchez Romero Sosa Alvarez Torres Ruiz Ramirez Flores Benitez Acosta Medina Herrera Suarez Aguirre Gutierrez Gimenez Molina Cabrera Rios Peralta Ortiz Cabrera Dominguez",
"Belgium": "Peeters Janssen Maes Jacobs Mertens Willems Claes Goossens Wouters de Smet Vermeulen Pauwels de Clercq Dubois Aerts Lambrechts Vandenberghe Coppens Segers Lemmens Thys",
"Scotland": "Smith Brown Wilson Campbell Stewart Thomson Martin Anderson MacDonald Scott Reid Ross Taylor Walker McLaughlin Henderson Hamilton Gray Duncan Ferguson McKay McKenzie Buchanan Cameron Kerr Douglas Millar",
"Turkey": "Yilmaz Kaya Demir Celik Sahin Yildiz Aydin Ozdemir Arslan Dogan Kilic Aslan Cetin Kara Koc Kurt Ozkan Simsek Polat Korkmaz Bulut Erdogan Gunes Aksu Tasdemir Calhanoglu",
"Wales": "Jones Williams Davies Evans Thomas Roberts Hughes Lewis Morgan Griffiths Richards Williams Owen Powell Price Jenkins Edwards Davies Rees James John Watkins",
"Denmark": "Jensen Nielsen Hansen Pedersen Andersen Christensen Larsen Sorensen Rasmussen Jorgensen Petersen Madsen Kristensen Olsen Thomsen Christiansen Poulsen Mogensen Knudsen Eriksen Frederiksen",
"Norway": "Hansen Johansen Olsen Larsen Andersen Pedersen Nilsen Kristiansen Jensen Karlsen Johnsen Pettersen Eriksen Berg Haugen Hagen Haland Sorloth Odegaard",
"Sweden": "Andersson Johansson Karlsson Nilsson Eriksson Larsson Olsson Persson Svensson Gustafsson Pettersson Jonsson Jansson Hansson Bengtsson Lindberg Lindqvist Isak Gyokeres Kulusevski",
"Poland": "Nowak Kowalski Wisniewski Wojcik Kowalczyk Kaminski Lewandowski Zielinski Dabrowski Szymanski Wozniak Kozlowski Jankowski Mazur Kwiatkowski Krol Wojtaszek",
"Croatia": "Horvat Kovacic Babic Maric Juric Novak Vidovic Peric Bozic Kovacevic Kolaric Modric Gvardiol Baturina Sucic Stanisic",
"Serbia": "Jovanovic Petrovic Nikolic Markovic Dordevic Stankovic Ilic Pavlovic Mitrovic Vlahovic Gudelj Lukic Milenkovic Zivkovic Samardzic",
"Uruguay": "Rodriguez Gonzalez Suarez Fernandez Bentancur Valverde Nunez Araujo Olivera Ugarte Pellistri De Arrascaeta",
"Colombia": "Rodriguez Gomez Martinez Lopez Sanchez Diaz Moreno Ramirez Cuadrado Davinson Lerma Sinisterra Castano",
"Mexico": "Hernandez Garcia Martinez Lopez Gonzalez Perez Sanchez Ramirez Flores Cruz Jimenez Lozano Alvarez Torres Pineda",
"USA": "Johnson Williams Brown Jones Miller Davis Rodriguez Martinez Anderson Taylor Pulisic Reyna McKennie Adams Balogun Weah",
"Japan": "Sato Suzuki Takahashi Tanaka Watanabe Ito Yamamoto Nakamura Kobayashi Kato Mitoma Kubo Endo Kamada Doan Taniguchi",
"South Korea": "Kim Lee Park Choi Jung Kang Cho Yun Jang Lim Son Hwang Hee-chan In-beom Min-jae",
"Nigeria": "Osimhen Lookman Chukwueze Iwobi Ndidi Etebo Aina Bassey Onyeka Moffi Ojo Akor Adams",
"Ghana": "Kudus Partey Ayew Amartey Sulemana Semenyo Salisu Djiku Gideon Mensah",
"Senegal": "Mane Sarr Dia Jakobs Gueye Camara Mendy Cisse Ndiaye Badiane Kouyate",
"Ivory Coast": "Kessie Haller Amad Pepe Boga Seri Bailly Singo Krasso Diomande",
"Morocco": "Hakimi Diaz Ounahi Amrabat Aguerd En-Nesyri Saiss Mazraoui Ziyech El Khannouss Ezzalzouli",
"Algeria": "Mahrez Bennacer Bounedjah Atal Guitane Zorgane Chaibi Amoura Ait-Nouri",
"Egypt": "Salah Marmoush Elneny Hegazi Ashour Trezeguet Fathi Mohsen Sobhi",
"Cameroon": "Mbeumo Onana Ngom Choupo-Moting Toko Ekambi Baleba Aboubakar Wooh",
"Ireland": "Kelleher Ebosele Scales Ogbene Azanu Idah Collins McAteer Manning Cullen",
"Switzerland": "Xhaka Shaqiri Freuler Embolo Akanji Elvedi Kobel Rieder Okafor Sierro",
"Austria": "Alaba Sabitzer Arnautovic Laimer Baumgartner Danso Posch Seiwald Wober",
"Czechia": "Schick Soucek Hranac Krejci Jurasek Coufal Hlozek Zima Vitik",
"Ukraine": "Mudryk Zinchenko Dovbyk Yarmolenko Lunin Malinovskyi Zabarnyi Sudakov",
"Greece": "Pavlidis Tzolis Bakasetas Mavropanos Kourbelis Giakoumakis Rota",
"Chile": "Sanchez Vidal Maripan Brereton Suazo Pulgar Nunez",
"Ecuador": "Caicedo Estupinan Valencia Plata Hincapie Pacho Gruezo",
"Paraguay": "Almiron Enciso Sanabria Gomez Balbuena Villasanti",
"Australia": "Ryan Irvine Boyle Duke Boyle Behich Duke Metcalfe",
"Canada": "Davies David Larin Buchanan Eustaquio Kone Millar",
"Slovakia": "Skriniar Lobotka Bozenik Hancko Haraslin Duda",
"Hungary": "Szoboszlai Szalai Nagy Varga Botka Styles Dardai",
"Romania": "Hagi Ratiu Dragusin Stanciu Coman Olaru Morutan",
"Bosnia": "Dzeko Pjanic Tabakovic Kolasinac Demirovic Krunić",
"Mali": "Bissouma Haidara Koita Doumbia Traore Djenepo Sissoko",
"DR Congo": "Mbemba Bakambu Wissa Tuanzebe Masuaku Kayembe",
"Guinea": "Keita Camara Sylla Guilavogui Moriba Conte",
"Burkina Faso": "Traore Tapsoba Kabore Ouattara Bandaogo Yago",
"Slovenia": "Oblak Sesko Bijol Stojanovic Ilicic Lovric Verbic",
"Finland": "Pukki Hradecky Kamara Jensen Lod Uronen",
"Iceland": "Sigurdsson Gudmundsson Willumsson Oskarsson Palsson",
"Israel": "Solomon Zahavi Glouza Peretz Abada Baribo",
"Tunisia": "Skhiri Sliti Khazri Meriah Drager Ben Slimane",
"Saudi Arabia": "Al-Dawsari Al-Owais Kanno Al-Buraikan Al-Amri",
"Qatar": "Afif Ali Hassan Khoukhi Al-Haydos",
"South Africa": "Tau Mokoena Zwane Nkota Foster Williams",
"Jamaica": "Antonio Bailey Reid Brown Leigh",
"Peru": "Guerrero Lapadula Advincula Carrillo Araujo",
"Venezuela": "Rondon Soteldo Murillo Machis Savarino",
"Costa Rica": "Navas Campbell Calvo Duarte Tejeda",
"Albania": "Broja Asllani Bajrami Hysaj Uzuni",
"Kosovo": "Muriqi Rashica Vojvoda Bytyqi Aliti",
"Georgia": "Kvaratskhelia Mikautadze Mamardashvili Lochoshvili",
"Armenia": "Mkhitaryan Spertsyan Barseghyan Ghazaryan",
"North Macedonia": "Elmas Bardhi Trajkovski Ristovski",
"Montenegro": "Jovetic Savic Mugosa Vukcevic",
"Northern Ireland": "Ballard Price Charles Lavery",
"Bulgaria": "Despodov Kirilov Krastev Chochev",
"Cyprus": "Pittas Kastanos Laifis Sotiriou",
"Kazakhstan": "Zaynutdinov Shomko Samorodov Vorogovskiy",
"Iran": "Taremi Azmoun Jahanbakhsh Ghoddos",
"Uzbekistan": "Shomurodov Fayzullaev Masharipov",
"New Zealand": "Wood Singh Bell Mata",
"Cape Verde": "Bebe Livramento Tavares",
"Haiti": "Nazon Pierrot Ade",
"Honduras": "Lozano Elis Rodriguez",
"Bolivia": "Vaca Moreno Miranda",
"Panama": "Carrasquilla Fajardo Murillo",
"Curacao": "Bacuna Janga Nepomuceno",
"Angola": "Mbala Zini Milson",
"Zambia": "Daka Sakala Banda",
"Kenya": "Olunga Wanyama Masika",
"Uganda": "Miangue Okwi Bayo",
"Equatorial Guinea": "Nsue Obiang Ganet",
"Gambia": "Jallow Ceesay Barrow",
"Sierra Leone": "Kamara Koroma Bundu",
"Togo": "Adebayor Djene Laba",
"Benin": "Mounie Doku Olaitan",
"Gabon": "Aubameyang Lemina Bouanga",
"Liberia": "Weah Tisdell",
"Comoros": "Mogni Bakari",
"Madagascar": "Rakotoharimalala Fontaine",
"Luxembourg": "Thill Rodrigues",
"Faroe Islands": "Olsen Edmundsson",
"Estonia": "Vassiljev Sappinen",
"Latvia": "Gutkovskis Ciganiks",
"Lithuania": "Slivka Lasickas",
"Belarus": "Lisakovich Yablonskiy",
"Moldova": "Damascan Cebotaru",
"Azerbaijan": "Mahmudov Emreli",
"Andorra": "Vieira Rebes",
"San Marino": "Berardi Golinucci",
"Liechtenstein": "Hasler Wolfinger",
"Malta": "Satariano Camenzuli",
"Gibraltar": "Chipolina Sergeant",
"Trinidad & Tobago": "Telfer Garcia",
"Suriname": "Haps Vlijter",
"Guinea-Bissau": "Baldé Embaló",
"Mauritania": "Sidi Thiam",
"Libya": "Elhouni Al Badri",
"Iraq": "Hussein Resan",
"Jordan": "Al-Tamari Olwan",
"Syria": "Osman Al Somah",
"Palestine": "Dabagh Wadi",
"Thailand": "Songkrasin Jaided",
"Vietnam": "Hai Van Hau",
"Indonesia": "Ferdinan Vikri",
"India": "Chhetri Jhingan",
"China PR": "Lei Yuning",
"El Salvador": "Roldan Menjivar",
"Guatemala": "Rubio Santis",
"Nicaragua": "Barrera Cadena",
"Dominican Republic": "Mariano Heinz",
"Puerto Rico": "Rodriguez Diaz",
"Martinique": "Parsemain Marajo",
"Guadeloupe": "Thuram Lina",
"French Guiana": "Epolo Ephestion",
"Namibia": "Shalulile Hotto",
"Botswana": "Kebatho Gaolaolwe",
"Zimbabwe": "Nakamba Musona",
"Mozambique": "Catamo Domingues",
"Tanzania": "Samatta Msuva",
"Rwanda": "Bizimana Hakizimana",
"Sudan": "Yousif Ramadan",
"Chad": "N'Douassel Marius",
}

NATIONALITY_POOL = list(FIRST.keys())


def _split(s):
    return [x for x in s.split() if x]


FIRST = {k: _split(v) for k, v in FIRST.items()}
LAST = {k: _split(v) for k, v in LAST.items()}

GENERIC_FIRST = _split("Alex Marco Daniel Lucas Mateo Andre Niko Tomas Rafael Omar Karim "
                       "Viktor Ivan Pablo Amir Diego Leon Milan Elias Noah Kai Bruno "
                       "Sebastian Gabriel Adrian Youssef Luka Emir Aron")
GENERIC_LAST = _split("Silva Costa Weber Kovac Novak Petrov Rossi Bianchi Nowak Horvat "
                      "Nagy Ivanov Fernandez Almeida Traore Demirev Bakker Sorensen "
                      "Garcia Lopez Martin Dubois Berger Ferreira Santos")


def make_name(rng, nat):
    f = FIRST.get(nat) or GENERIC_FIRST
    l = LAST.get(nat) or GENERIC_LAST
    first = rng.choice(f)
    last = rng.choice(l)
    # occasionally a two-part first name
    if rng.random() < 0.08:
        first = first + "-" + rng.choice(f)
    return f"{first} {last}"


def make_moniker(rng, nat):
    """Short nickname/known-as, used occasionally."""
    f = FIRST.get(nat) or GENERIC_FIRST
    return rng.choice(f)


MANAGER_FIRST = _split("Roberto Julian Marco Antonio Luis Thomas Erik Paulo Rafael Daniel "
                       "Steven Graham Darren Vincenzo Sergio Ruben Nuno Oliver Frank "
                       "Andoni Mikel Thiago Graham Liam Wayne Michael Patrick")
MANAGER_LAST = _split("De Rossi Mancini Arteta Amorim Slot Kompany Glasner Emery Conte "
                      "Maresca Iraola Howe Farke Wildsmith McKenna Cifuentes Corberan "
                      "Mourinho Guardiola Klopp Ancelotti Ferguson Wenger Davies Cooper "
                      "Parker Edwards Manning Boyle Shaw Turner Reid Doyle Clarke")


def make_manager_name(rng):
    return f"{rng.choice(MANAGER_FIRST)} {rng.choice(MANAGER_LAST)}"


STAFF_FIRST = MANAGER_FIRST
STAFF_LAST = MANAGER_LAST


def make_staff_name(rng, nat):
    f = FIRST.get(nat) or GENERIC_FIRST
    l = LAST.get(nat) or GENERIC_LAST
    return f"{rng.choice(f)} {rng.choice(l)}"
